package gpugen

import (
	"fmt"
	"strings"
)

// Emit generates GPU kernel source for the given ISA and backend.
func Emit(isa ISA, backend Backend) string {
	var b strings.Builder
	e := &emitter{isa: isa, backend: backend, b: &b}
	e.emit()
	return b.String()
}

type emitter struct {
	isa     ISA
	backend Backend
	b       *strings.Builder
}

func (e *emitter) w(format string, args ...any) {
	fmt.Fprintf(e.b, format, args...)
}

func (e *emitter) emit() {
	e.emitHeader()
	e.emitCostTable()
	e.emitExecOp()
	e.emitRunSeq()
	e.emitKernel()
}

// --- type mapping per backend ---

func (e *emitter) u8() string {
	switch e.backend {
	case CUDA:
		return "uint8_t"
	case Vulkan:
		return "uint" // GLSL has no 8-bit type; mask with & 0xFF
	default: // Metal, OpenCL
		return "uchar"
	}
}

func (e *emitter) u16() string {
	switch e.backend {
	case CUDA:
		return "uint16_t"
	case Vulkan:
		return "uint"
	default:
		return "ushort"
	}
}

func (e *emitter) i16() string {
	switch e.backend {
	case CUDA:
		return "int16_t"
	case Vulkan:
		return "int"
	default:
		return "short"
	}
}

func (e *emitter) typeStr(t Type) string {
	switch t {
	case U8:
		return e.u8()
	case U16:
		return e.u16()
	case Bool:
		return e.boolType()
	default:
		return e.u8()
	}
}

func (e *emitter) u32() string {
	switch e.backend {
	case CUDA:
		return "uint32_t"
	default: // Metal, OpenCL, Vulkan
		return "uint"
	}
}

func (e *emitter) u64() string {
	switch e.backend {
	case CUDA:
		return "uint64_t"
	case Vulkan:
		return "uint64_t" // requires GL_EXT_shader_explicit_arithmetic_types_int64
	default: // Metal, OpenCL
		return "ulong"
	}
}

func (e *emitter) boolType() string {
	switch e.backend {
	case OpenCL:
		return "int"
	default: // CUDA, Metal, Vulkan
		return "bool"
	}
}

func (e *emitter) boolFalse() string {
	if e.backend == OpenCL {
		return "0"
	}
	return "false"
}

// vulkan needs explicit masking since all "u8" ops are actually uint
func (e *emitter) isVulkan() bool {
	return e.backend == Vulkan
}

// expandTypes replaces UINT8/UINT16/INT16 placeholders with backend types.
// For Vulkan (GLSL), also converts C-style casts (type)x to type(x).
func (e *emitter) expandTypes(body string) string {
	r := strings.NewReplacer(
		"UINT8", e.u8(),
		"UINT16", e.u16(),
		"INT16", e.i16(),
	)
	body = r.Replace(body)
	if e.backend == Vulkan {
		body = cCastToGLSL(body)
	}
	return body
}

// cCastToGLSL converts C-style casts like (uint)expr to uint(expr).
// Handles: (uint), (int), (bool)
func cCastToGLSL(s string) string {
	for _, typ := range []string{"uint", "int", "bool"} {
		cast := "(" + typ + ")"
		for {
			idx := strings.Index(s, cast)
			if idx == -1 {
				break
			}
			// Find the expression after the cast — take until space, semicolon, comma, ), or operator
			after := idx + len(cast)
			// Skip whitespace
			for after < len(s) && s[after] == ' ' {
				after++
			}
			// Find end of expression token (simple: one identifier/number or parenthesized expr)
			end := after
			if end < len(s) && s[end] == '(' {
				// Parenthesized: find matching close
				depth := 1
				end++
				for end < len(s) && depth > 0 {
					if s[end] == '(' {
						depth++
					} else if s[end] == ')' {
						depth--
					}
					end++
				}
			} else {
				// Simple token
				for end < len(s) && (isIdent(s[end]) || s[end] == '.') {
					end++
				}
			}
			expr := s[after:end]
			s = s[:idx] + typ + "(" + expr + ")" + s[end:]
		}
	}
	return s
}

// regType returns the C type for a register.
func (e *emitter) regType(t Type) string {
	switch t {
	case U8:
		return e.u8()
	case U16:
		return e.u16()
	case Bool:
		return e.boolType()
	default:
		return e.u8()
	}
}

// --- header ---

func (e *emitter) emitHeader() {
	e.w("// %s — auto-generated by gpugen for %s\n", e.isa.Name, e.backend)
	e.w("// %d ops, %d registers\n\n", len(e.isa.Ops), len(e.isa.State))

	switch e.backend {
	case CUDA:
		e.w("#include <cstdint>\n\n")
		e.w("#define NUM_OPS %d\n\n", len(e.isa.Ops))
	case Metal:
		e.w("#include <metal_stdlib>\nusing namespace metal;\n\n")
		e.w("#define NUM_OPS %d\n\n", len(e.isa.Ops))
	case OpenCL:
		e.w("#define NUM_OPS %d\n\n", len(e.isa.Ops))
	case Vulkan:
		e.w("#version 450\n")
		e.w("#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require\n")
		e.w("#extension GL_KHR_shader_subgroup_basic : enable\n\n")
		e.w("layout(local_size_x = 256) in;\n\n")
		e.w("#define NUM_OPS %d\n\n", len(e.isa.Ops))
	}
}

// --- cost table ---

func (e *emitter) emitCostTable() {
	switch e.backend {
	case CUDA:
		e.w("__constant__ %s opCost[NUM_OPS] = {", e.u8())
	case Metal:
		e.w("constant %s opCost[NUM_OPS] = {", e.u8())
	case Vulkan:
		e.w("const uint opCost[NUM_OPS] = uint[NUM_OPS](")
	case OpenCL:
		// OpenCL: embedded in kernel as __constant
		return
	}
	for i, op := range e.isa.Ops {
		if i > 0 {
			e.w(",")
		}
		e.w("%d", op.Cost)
	}
	if e.backend == Vulkan {
		e.w(");\n\n")
	} else {
		e.w("};\n\n")
	}
}

// --- exec_op ---

func (e *emitter) emitExecOp() {
	// Function signature
	switch e.backend {
	case CUDA:
		e.w("__device__ ")
	case Metal:
		e.w("static inline ")
	}
	e.w("void exec_op(%s op", e.u8())
	for _, reg := range e.isa.State {
		switch e.backend {
		case Metal:
			e.w(", thread %s &%s", e.regType(reg.Type), reg.Name)
		case Vulkan:
			e.w(", inout %s %s", e.regType(reg.Type), reg.Name)
		default:
			e.w(", %s *%s", e.regType(reg.Type), reg.Name)
		}
	}
	e.w(") {\n")

	// Local vars for temporaries used in op bodies
	e.w("    %s r; %s c; %s bit;\n", e.u16(), e.u16(), e.u8())
	// Additional locals declared by ISA (for multi-register ops)
	for _, v := range e.isa.Locals {
		e.w("    %s %s;\n", e.typeStr(v.Type), v.Name)
	}
	e.w("    switch (op) {\n")

	for i, op := range e.isa.Ops {
		e.w("    case %d: /* %s */\n", i, op.Name)
		body := e.expandTypes(op.Body)
		// For CUDA/OpenCL, dereference pointers (Metal/Vulkan use references)
		if e.backend != Metal && e.backend != Vulkan {
			body = e.derefBody(body)
		}
		e.w("        %s break;\n", body)
	}
	e.w("    }\n}\n\n")
}

// derefBody converts "a = ..." to "*a = ..." for pointer-based backends.
func (e *emitter) derefBody(body string) string {
	for _, reg := range e.isa.State {
		// Replace register accesses with pointer dereferences.
		// We need to be careful not to replace substrings of other identifiers.
		// Simple approach: replace word-boundary matches.
		body = replaceWord(body, reg.Name, "*"+reg.Name)
	}
	return body
}

// replaceWord replaces whole-word occurrences of old with new in s.
func replaceWord(s, old, new string) string {
	var b strings.Builder
	i := 0
	for i < len(s) {
		idx := strings.Index(s[i:], old)
		if idx == -1 {
			b.WriteString(s[i:])
			break
		}
		pos := i + idx
		// Check word boundary before
		if pos > 0 && isIdent(s[pos-1]) {
			b.WriteString(s[i : pos+len(old)])
			i = pos + len(old)
			continue
		}
		// Check word boundary after
		after := pos + len(old)
		if after < len(s) && isIdent(s[after]) {
			b.WriteString(s[i : pos+len(old)])
			i = pos + len(old)
			continue
		}
		b.WriteString(s[i:pos])
		b.WriteString(new)
		i = after
	}
	return b.String()
}

func isIdent(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_'
}

// --- run_seq ---

func (e *emitter) emitRunSeq() {
	switch e.backend {
	case CUDA:
		e.w("__device__ ")
	case Metal:
		e.w("static inline ")
	}
	// GLSL reserves "input" — use "inp" for Vulkan
	inputParam := "input"
	if e.backend == Vulkan {
		inputParam = "inp"
	}
	e.w("%s run_seq(", e.u8())
	switch e.backend {
	case Metal:
		e.w("thread %s *ops, int len, %s %s", e.u8(), e.u8(), inputParam)
	case Vulkan:
		e.w("uint ops[12], int len, uint %s", inputParam)
	default:
		e.w("%s *ops, int len, %s %s", e.u8(), e.u8(), inputParam)
	}
	e.w(") {\n")

	// Declare state registers
	for _, reg := range e.isa.State {
		if reg.Name == e.isa.InputReg {
			e.w("    %s %s = %s;\n", e.regType(reg.Type), reg.Name, inputParam)
		} else if reg.Type == Bool {
			e.w("    %s %s = %s;\n", e.regType(reg.Type), reg.Name, e.boolFalse())
		} else {
			e.w("    %s %s = 0;\n", e.regType(reg.Type), reg.Name)
		}
	}

	e.w("    for (int i = 0; i < len; i++) exec_op(ops[i]")
	for _, reg := range e.isa.State {
		if e.backend == Metal || e.backend == Vulkan {
			e.w(", %s", reg.Name)
		} else {
			e.w(", &%s", reg.Name)
		}
	}
	e.w(");\n")
	if e.backend == Vulkan {
		e.w("    return %s & 0xFF;\n", e.isa.OutputReg)
	} else {
		e.w("    return %s;\n", e.isa.OutputReg)
	}
	e.w("}\n\n")
}

// --- kernel ---

func (e *emitter) emitKernel() {
	switch e.backend {
	case CUDA:
		e.emitCUDAKernel()
	case Metal:
		e.emitMetalKernel()
	case OpenCL:
		e.emitOpenCLKernel()
	case Vulkan:
		e.emitVulkanKernel()
	}
}

func (e *emitter) emitCUDAKernel() {
	e.w("__global__ void %s_kernel(%s k, int seqLen, %s offset, %s count,\n",
		e.isa.Name, e.u8(), e.u64(), e.u64())
	e.w("                          %s *bestScore, %s *bestIdx) {\n", e.u32(), e.u64())
	e.w("    %s tid = blockIdx.x * (%s)blockDim.x + threadIdx.x;\n", e.u64(), e.u64())
	e.w("    if (tid >= count) return;\n\n")
	e.emitKernelBody("seqIdx", "tid", "offset")
	e.w("    uint32_t score = ((uint32_t)seqLen << 16) | cost;\n")
	e.w("    uint32_t old = atomicMin(bestScore, score);\n")
	e.w("    if (score <= old) atomicExch((unsigned long long *)bestIdx, (unsigned long long)seqIdx);\n")
	e.w("}\n")
}

func (e *emitter) emitMetalKernel() {
	e.w("struct MuloptArgs {\n")
	e.w("    uint k;\n    int seqLen;\n    ulong offset;\n    ulong count;\n};\n\n")
	e.w("kernel void %s_kernel(\n", e.isa.Name)
	e.w("    constant MuloptArgs &args [[buffer(0)]],\n")
	e.w("    device atomic_uint *bestScore [[buffer(1)]],\n")
	e.w("    device atomic_uint *bestIdxLo [[buffer(2)]],\n")
	e.w("    device atomic_uint *bestIdxHi [[buffer(3)]],\n")
	e.w("    uint tid [[thread_position_in_grid]]\n) {\n")
	e.w("    if (tid >= args.count) return;\n")
	e.w("    int seqLen = args.seqLen;\n")
	e.w("    %s k = (%s)args.k;\n\n", e.u8(), e.u8())
	e.emitKernelBody("seqIdx", "tid", "args.offset")
	e.w("    uint score = ((uint)seqLen << 16) | cost;\n")
	e.w("    uint old = atomic_fetch_min_explicit(bestScore, score, memory_order_relaxed);\n")
	e.w("    if (score <= old) {\n")
	e.w("        atomic_store_explicit(bestIdxLo, (uint)(seqIdx & 0xFFFFFFFF), memory_order_relaxed);\n")
	e.w("        atomic_store_explicit(bestIdxHi, (uint)(seqIdx >> 32), memory_order_relaxed);\n")
	e.w("    }\n")
	e.w("}\n")
}

func (e *emitter) emitOpenCLKernel() {
	// OpenCL: cost table inside kernel
	e.w("__constant %s opCostTbl[NUM_OPS] = {", e.u8())
	for i, op := range e.isa.Ops {
		if i > 0 {
			e.w(",")
		}
		e.w("%d", op.Cost)
	}
	e.w("};\n\n")

	e.w("__kernel void %s_kernel(%s k, int seqLen, %s offset, %s count,\n",
		e.isa.Name, e.u8(), e.u64(), e.u64())
	e.w("                        __global %s *bestScore, __global %s *bestIdx) {\n",
		e.u32(), e.u64())
	e.w("    %s tid = get_global_id(0);\n", e.u64())
	e.w("    if (tid >= count) return;\n\n")
	e.emitKernelBody("seqIdx", "tid", "offset")
	e.w("    %s score = ((%s)seqLen << 16) | cost;\n", e.u32(), e.u32())
	e.w("    atomic_min(bestScore, score);\n")
	e.w("    if (score <= *bestScore) bestIdx[0] = seqIdx;\n")
	e.w("}\n")
}

func (e *emitter) emitVulkanKernel() {
	// SSBO bindings
	e.w("layout(binding = 0) buffer Args {\n")
	e.w("    uint k;\n    int seqLen;\n    uint64_t offset;\n    uint64_t count;\n")
	e.w("} args;\n\n")
	e.w("layout(binding = 1) buffer Result {\n")
	e.w("    uint bestScore;\n    uint bestIdxLo;\n    uint bestIdxHi;\n")
	e.w("} result;\n\n")

	e.w("void main() {\n")
	e.w("    uint tid = gl_GlobalInvocationID.x;\n")
	e.w("    if (tid >= args.count) return;\n")
	e.w("    int seqLen = args.seqLen;\n")
	e.w("    uint k = args.k;\n\n")
	e.emitKernelBody("seqIdx", "tid", "args.offset")
	e.w("    uint score = (uint(seqLen) << 16) | cost;\n")
	e.w("    atomicMin(result.bestScore, score);\n")
	e.w("    if (score <= result.bestScore) {\n")
	e.w("        result.bestIdxLo = uint(seqIdx & uint64_t(0xFFFFFFFF));\n")
	e.w("        result.bestIdxHi = uint(seqIdx >> 32);\n")
	e.w("    }\n")
	e.w("}\n")
}

// emitKernelBody emits the shared logic: decode, quickcheck, verify, cost.
func (e *emitter) emitKernelBody(seqVar, tidVar, offsetExpr string) {
	e.w("    %s %s = %s + %s;\n", e.u64(), seqVar, offsetExpr, tidVar)
	e.w("    %s ops[12];\n", e.u8())
	e.w("    %s tmp = %s;\n", e.u64(), seqVar)
	e.w("    for (int i = seqLen - 1; i >= 0; i--) {\n")
	if e.backend == Vulkan {
		e.w("        ops[i] = uint(tmp %% NUM_OPS);\n")
	} else {
		e.w("        ops[i] = (%s)(tmp %% NUM_OPS);\n", e.u8())
	}
	e.w("        tmp /= NUM_OPS;\n")
	e.w("    }\n\n")

	// QuickCheck — must cast (N * k) to u8 to match run_seq return type
	// Vulkan uses & 0xFF (no 8-bit type), others use (uchar)/(uint8_t) cast
	for _, v := range e.isa.QuickCheck {
		if e.backend == Vulkan {
			e.w("    if (run_seq(ops, seqLen, %d) != ((%d * k) & 0xFF)) return;\n", v, v)
		} else {
			e.w("    if (run_seq(ops, seqLen, %d) != (%s)(%d * k)) return;\n", v, e.u8(), v)
		}
	}

	// Full verify — "input" is reserved in GLSL
	loopVar := "input"
	if e.backend == Vulkan {
		loopVar = "inp"
	}
	e.w("\n    for (int %s = 0; %s < 256; %s++) {\n", loopVar, loopVar, loopVar)
	if e.backend == Vulkan {
		e.w("        if (run_seq(ops, seqLen, uint(%s)) != ((%s * k) & 0xFF)) return;\n", loopVar, loopVar)
	} else {
		e.w("        if (run_seq(ops, seqLen, (%s)%s) != (%s)(%s * k)) return;\n", e.u8(), loopVar, e.u8(), loopVar)
	}
	e.w("    }\n\n")

	// Cost
	costArr := "opCost"
	if e.backend == OpenCL {
		costArr = "opCostTbl"
	}
	e.w("    %s cost = 0;\n", e.u32())
	e.w("    for (int i = 0; i < seqLen; i++) cost += %s[ops[i]];\n", costArr)
}
