; Z80 Optimal Constant Division Library (8-bit: A / K → A, floor)
; Generated by scripts/gen_div8_library.py from div8_optimal.json
; (Analytical multiply-and-shift + GPU-verified sequences)
;
; 254 constants (k=2..255), sequences in CORRECT execution order.
; 51 fall-through chains (genuine suffix relationships only, verified entries only).
; WARNING: 56 entries failed Z80 simulation (tagged CAUTION below, excluded from chains).

;
; Convention:
;   Input:  A = dividend (unsigned 8-bit, 0..255)
;   Output: A = floor(A / K)
;   Clobber: varies (B, C, H, L, F) — see per-entry comment
;
; Usage:
;   LD A, (dividend)
;   CALL div_42
;   ; A = dividend / 42 (floor)
;
; Pseudo-op expansions:
;   SWAP_HL  → LD A,L / LD L,H / LD H,A  (put L into H, zero L: HL = A<<8)
;   SUB HL,BC → OR A / SBC HL,BC          (carry-free HL -= BC)
;
; Note: T-state counts are for original optimizer sequences.
; Expanded pseudo-ops add ~4-8T per occurrence vs. the listed T-states.
;
; Repository: https://github.com/oisee/z80-optimizer
; License: MIT
;
; --- Chain: ÷33 → ÷32 → ÷16 → ÷8 → ÷4 → ÷2 ---
div_33:  ; ÷33  (17 insts, 175T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    ; SWAP_HL (expanded):
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
div_32:  ; ÷32  (5 insts, 40T | clobbers: A, F)
    SRL A
div_16:  ; ÷16  (4 insts, 32T | clobbers: A, F)
    SRL A
div_8:  ; ÷8  (3 insts, 24T | clobbers: A, F)
    SRL A
div_4:  ; ÷4  (2 insts, 16T | clobbers: A, F)
    SRL A
div_2:  ; ÷2  (1 insts, 8T | clobbers: A, F)
    SRL A
    RET

div_65:  ; ÷65  (14 insts, 123T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ; SWAP_HL (expanded):
    LD A,L
    LD L,H
    LD H,A
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    SRL A
    JRS div_32

div_73:  ; ÷73  (20 insts, 177T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    JRS div_32

div_74:  ; ÷74  (18 insts, 162T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_32

div_78:  ; ÷78  (21 insts, 188T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_32

div_81:  ; ÷81  (21 insts, 188T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    JRS div_32

div_85:  ; ÷85  (19 insts, 166T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    JRS div_32

div_89:  ; ÷89  (20 insts, 181T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    JRS div_32

div_99:  ; ÷99  (18 insts, 158T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_32

div_17:  ; ÷17  (18 insts, 165T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_16

div_37:  ; ÷37  (17 insts, 154T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_16

div_66:  ; ÷66  (18 insts, 162T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_16

div_100:  ; ÷100  (15 insts, 128T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_16

div_102:  ; ÷102  (17 insts, 147T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_16

div_110:  ; ÷110  (18 insts, 158T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_16

div_111:  ; ÷111  (15 insts, 128T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_16

div_116:  ; ÷116  (17 insts, 151T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_16

div_22:  ; ÷22  (18 insts, 169T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_8

div_26:  ; ÷26  (15 insts, 135T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_8

div_34:  ; ÷34  (17 insts, 154T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_36:  ; ÷36  (15 insts, 131T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_50:  ; ÷50  (14 insts, 120T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_58:  ; ÷58  (16 insts, 143T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_8

div_70:  ; ÷70  (16 insts, 147T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_8

div_82:  ; ÷82  (13 insts, 109T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_84:  ; ÷84  (15 insts, 128T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_92:  ; ÷92  (16 insts, 139T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_98:  ; ÷98  (13 insts, 109T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_106:  ; ÷106  (15 insts, 132T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_8

div_108:  ; ÷108  (13 insts, 109T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_118:  ; ÷118  (15 insts, 128T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_8

div_13:  ; ÷13  (14 insts, 127T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_4

div_18:  ; ÷18  (14 insts, 123T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_25:  ; ÷25  (13 insts, 112T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_41:  ; ÷41  (12 insts, 101T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_42:  ; ÷42  (14 insts, 120T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_54:  ; ÷54  (12 insts, 101T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_68:  ; ÷68  (16 insts, 143T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_79:  ; ÷79  (11 insts, 90T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_90:  ; ÷90  (13 insts, 113T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_4

div_112:  ; ÷112  (15 insts, 128T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_114:  ; ÷114  (10 insts, 79T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_4

div_9:  ; ÷9  (13 insts, 115T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

div_10:  ; ÷10  (15 insts, 138T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_2

div_24:  ; ÷24  (14 insts, 123T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

div_27:  ; ÷27  (11 insts, 93T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

div_44:  ; ÷44  (14 insts, 124T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    JRS div_2

div_56:  ; ÷56  (14 insts, 120T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

div_57:  ; ÷57  (9 insts, 71T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

div_94:  ; ÷94  (11 insts, 90T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

div_120:  ; ÷120  (15 insts, 128T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    JRS div_2

; CAUTION: div_3 — Z80 simulation FAILED (a_in=3: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_3:  ; ÷3  (16 insts, 141T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    RET

; CAUTION: div_5 — Z80 simulation FAILED (a_in=5: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_5:  ; ÷5  (17 insts, 149T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    RET

div_6:  ; ÷6  (14 insts, 126T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_7 — Z80 simulation FAILED (a_in=1: got 2, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_7:  ; ÷7  (16 insts, 128T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_11 — Z80 simulation FAILED (a_in=1: got 5, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_11:  ; ÷11  (20 insts, 169T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_12:  ; ÷12  (13 insts, 115T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    RET

; CAUTION: div_14 — Z80 simulation FAILED (a_in=1: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_14:  ; ÷14  (17 insts, 136T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_15 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_15:  ; ÷15  (15 insts, 114T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_19 — Z80 simulation FAILED (a_in=19: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_19:  ; ÷19  (12 insts, 97T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    RET

div_20:  ; ÷20  (13 insts, 112T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_21 — Z80 simulation FAILED (a_in=1: got 2, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_21:  ; ÷21  (20 insts, 170T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_23 — Z80 simulation FAILED (a_in=1: got 2, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_23:  ; ÷23  (20 insts, 166T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_28:  ; ÷28  (13 insts, 112T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    RET

; CAUTION: div_29 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_29:  ; ÷29  (18 insts, 144T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_30 — Z80 simulation FAILED (a_in=3: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_30:  ; ÷30  (16 insts, 122T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_31 — Z80 simulation FAILED (a_in=6: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_31:  ; ÷31  (15 insts, 111T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_35 — Z80 simulation FAILED (a_in=35: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_35:  ; ÷35  (20 insts, 177T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_38 — Z80 simulation FAILED (a_in=38: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_38:  ; ÷38  (13 insts, 105T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    RET

; CAUTION: div_39 — Z80 simulation FAILED (a_in=1: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_39:  ; ÷39  (22 insts, 185T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_40:  ; ÷40  (12 insts, 101T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_43 — Z80 simulation FAILED (a_in=86: got 0, expected 2)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_43:  ; ÷43  (16 insts, 127T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ; SWAP_HL (expanded):
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_45 — Z80 simulation FAILED (a_in=1: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_45:  ; ÷45  (22 insts, 185T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_46 — Z80 simulation FAILED (a_in=1: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_46:  ; ÷46  (21 insts, 174T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_47 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_47:  ; ÷47  (20 insts, 167T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_48:  ; ÷48  (14 insts, 120T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_49 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_49:  ; ÷49  (20 insts, 167T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_51 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_51:  ; ÷51  (19 insts, 152T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_52:  ; ÷52  (11 insts, 90T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_53 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_53:  ; ÷53  (20 insts, 163T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_55 — Z80 simulation FAILED (a_in=3: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_55:  ; ÷55  (19 insts, 152T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_59 — Z80 simulation FAILED (a_in=5: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_59:  ; ÷59  (18 insts, 141T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_60 — Z80 simulation FAILED (a_in=6: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_60:  ; ÷60  (17 insts, 130T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_61 — Z80 simulation FAILED (a_in=7: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_61:  ; ÷61  (17 insts, 130T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_62 — Z80 simulation FAILED (a_in=11: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_62:  ; ÷62  (16 insts, 119T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_63 — Z80 simulation FAILED (a_in=16: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_63:  ; ÷63  (15 insts, 108T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_64:  ; ÷64  (5 insts, 37T | clobbers: A, F, H, L)
    LD H,0
    LD L,A
    ADD HL,HL
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_67 — Z80 simulation FAILED (a_in=67: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_67:  ; ÷67  (21 insts, 181T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_69 — Z80 simulation FAILED (a_in=69: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_69:  ; ÷69  (19 insts, 162T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_71 — Z80 simulation FAILED (a_in=71: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_71:  ; ÷71  (21 insts, 181T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_72:  ; ÷72  (14 insts, 120T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    RET

; CAUTION: div_75 — Z80 simulation FAILED (a_in=75: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_75:  ; ÷75  (21 insts, 181T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_76 — Z80 simulation FAILED (a_in=76: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_76:  ; ÷76  (14 insts, 113T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_77 — Z80 simulation FAILED (a_in=77: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_77:  ; ÷77  (21 insts, 185T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_80:  ; ÷80  (11 insts, 90T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    RET

; CAUTION: div_83 — Z80 simulation FAILED (a_in=83: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_83:  ; ÷83  (18 insts, 151T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_86:  ; ÷86  (8 insts, 60T | clobbers: A, C, F, H, L)
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_87 — Z80 simulation FAILED (a_in=87: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_87:  ; ÷87  (20 insts, 174T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_88:  ; ÷88  (12 insts, 98T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_91 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_91:  ; ÷91  (22 insts, 182T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_93 — Z80 simulation FAILED (a_in=2: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_93:  ; ÷93  (21 insts, 171T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_95 — Z80 simulation FAILED (a_in=3: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_95:  ; ÷95  (22 insts, 182T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_96:  ; ÷96  (13 insts, 109T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_97 — Z80 simulation FAILED (a_in=3: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_97:  ; ÷97  (21 insts, 171T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_101 — Z80 simulation FAILED (a_in=4: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_101:  ; ÷101  (21 insts, 171T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_103 — Z80 simulation FAILED (a_in=103: got 0, expected 1)
; Method: double_mul_shift — sequence may be incorrect for this input.
div_103:  ; ÷103  (19 insts, 154T | clobbers: A, C, F, H, L)
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ; SWAP_HL (expanded):
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_104:  ; ÷104  (10 insts, 79T | clobbers: A, C, F, H, L)
    SRL A
    SRL A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    RET

; CAUTION: div_105 — Z80 simulation FAILED (a_in=4: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_105:  ; ÷105  (21 insts, 171T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_107 — Z80 simulation FAILED (a_in=4: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_107:  ; ÷107  (21 insts, 171T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_109 — Z80 simulation FAILED (a_in=5: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_109:  ; ÷109  (20 insts, 164T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_113 — Z80 simulation FAILED (a_in=7: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_113:  ; ÷113  (19 insts, 149T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_115 — Z80 simulation FAILED (a_in=9: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_115:  ; ÷115  (19 insts, 153T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_117 — Z80 simulation FAILED (a_in=8: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_117:  ; ÷117  (19 insts, 149T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_119 — Z80 simulation FAILED (a_in=10: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_119:  ; ÷119  (18 insts, 138T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_121 — Z80 simulation FAILED (a_in=16: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_121:  ; ÷121  (18 insts, 142T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ; SUB HL,BC (expanded):
    OR A
    SBC HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_122 — Z80 simulation FAILED (a_in=13: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_122:  ; ÷122  (18 insts, 138T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_123 — Z80 simulation FAILED (a_in=16: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_123:  ; ÷123  (18 insts, 138T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_124 — Z80 simulation FAILED (a_in=22: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_124:  ; ÷124  (17 insts, 127T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_125 — Z80 simulation FAILED (a_in=22: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_125:  ; ÷125  (17 insts, 127T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_126 — Z80 simulation FAILED (a_in=32: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_126:  ; ÷126  (16 insts, 116T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

; CAUTION: div_127 — Z80 simulation FAILED (a_in=43: got 1, expected 0)
; Method: mul_add256_shift — sequence may be incorrect for this input.
div_127:  ; ÷127  (15 insts, 105T | clobbers: A, B, C, F, H, L)
    LD B,A
    LD H,0
    LD L,A
    LD C,A
    ADD HL,BC
    ADD HL,BC
    LD A,H
    ADD A,B
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    SRL A
    RET

div_128:  ; ÷128  (4 insts, 26T | clobbers: A, F, H, L)
    LD H,0
    LD L,A
    ADD HL,HL
    LD A,H
    RET

div_129:  ; ÷129  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,127
    ADC A,B
    SBC A,A
    AND 1
    RET

div_130:  ; ÷130  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,126
    ADC A,B
    SBC A,A
    AND 1
    RET

div_131:  ; ÷131  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,125
    ADC A,B
    SBC A,A
    AND 1
    RET

div_132:  ; ÷132  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,124
    ADC A,B
    SBC A,A
    AND 1
    RET

div_133:  ; ÷133  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,123
    ADC A,B
    SBC A,A
    AND 1
    RET

div_134:  ; ÷134  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,122
    ADC A,B
    SBC A,A
    AND 1
    RET

div_135:  ; ÷135  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,121
    ADC A,B
    SBC A,A
    AND 1
    RET

div_136:  ; ÷136  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,120
    ADC A,B
    SBC A,A
    AND 1
    RET

div_137:  ; ÷137  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,119
    ADC A,B
    SBC A,A
    AND 1
    RET

div_138:  ; ÷138  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,118
    ADC A,B
    SBC A,A
    AND 1
    RET

div_139:  ; ÷139  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,117
    ADC A,B
    SBC A,A
    AND 1
    RET

div_140:  ; ÷140  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,116
    ADC A,B
    SBC A,A
    AND 1
    RET

div_141:  ; ÷141  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,115
    ADC A,B
    SBC A,A
    AND 1
    RET

div_142:  ; ÷142  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,114
    ADC A,B
    SBC A,A
    AND 1
    RET

div_143:  ; ÷143  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,113
    ADC A,B
    SBC A,A
    AND 1
    RET

div_144:  ; ÷144  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,112
    ADC A,B
    SBC A,A
    AND 1
    RET

div_145:  ; ÷145  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,111
    ADC A,B
    SBC A,A
    AND 1
    RET

div_146:  ; ÷146  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,110
    ADC A,B
    SBC A,A
    AND 1
    RET

div_147:  ; ÷147  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,109
    ADC A,B
    SBC A,A
    AND 1
    RET

div_148:  ; ÷148  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,108
    ADC A,B
    SBC A,A
    AND 1
    RET

div_149:  ; ÷149  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,107
    ADC A,B
    SBC A,A
    AND 1
    RET

div_150:  ; ÷150  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,106
    ADC A,B
    SBC A,A
    AND 1
    RET

div_151:  ; ÷151  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,105
    ADC A,B
    SBC A,A
    AND 1
    RET

div_152:  ; ÷152  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,104
    ADC A,B
    SBC A,A
    AND 1
    RET

div_153:  ; ÷153  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,103
    ADC A,B
    SBC A,A
    AND 1
    RET

div_154:  ; ÷154  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,102
    ADC A,B
    SBC A,A
    AND 1
    RET

div_155:  ; ÷155  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,101
    ADC A,B
    SBC A,A
    AND 1
    RET

div_156:  ; ÷156  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,100
    ADC A,B
    SBC A,A
    AND 1
    RET

div_157:  ; ÷157  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,99
    ADC A,B
    SBC A,A
    AND 1
    RET

div_158:  ; ÷158  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,98
    ADC A,B
    SBC A,A
    AND 1
    RET

div_159:  ; ÷159  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,97
    ADC A,B
    SBC A,A
    AND 1
    RET

div_160:  ; ÷160  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,96
    ADC A,B
    SBC A,A
    AND 1
    RET

div_161:  ; ÷161  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,95
    ADC A,B
    SBC A,A
    AND 1
    RET

div_162:  ; ÷162  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,94
    ADC A,B
    SBC A,A
    AND 1
    RET

div_163:  ; ÷163  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,93
    ADC A,B
    SBC A,A
    AND 1
    RET

div_164:  ; ÷164  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,92
    ADC A,B
    SBC A,A
    AND 1
    RET

div_165:  ; ÷165  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,91
    ADC A,B
    SBC A,A
    AND 1
    RET

div_166:  ; ÷166  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,90
    ADC A,B
    SBC A,A
    AND 1
    RET

div_167:  ; ÷167  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,89
    ADC A,B
    SBC A,A
    AND 1
    RET

div_168:  ; ÷168  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,88
    ADC A,B
    SBC A,A
    AND 1
    RET

div_169:  ; ÷169  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,87
    ADC A,B
    SBC A,A
    AND 1
    RET

div_170:  ; ÷170  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,86
    ADC A,B
    SBC A,A
    AND 1
    RET

div_171:  ; ÷171  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,85
    ADC A,B
    SBC A,A
    AND 1
    RET

div_172:  ; ÷172  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,84
    ADC A,B
    SBC A,A
    AND 1
    RET

div_173:  ; ÷173  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,83
    ADC A,B
    SBC A,A
    AND 1
    RET

div_174:  ; ÷174  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,82
    ADC A,B
    SBC A,A
    AND 1
    RET

div_175:  ; ÷175  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,81
    ADC A,B
    SBC A,A
    AND 1
    RET

div_176:  ; ÷176  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,80
    ADC A,B
    SBC A,A
    AND 1
    RET

div_177:  ; ÷177  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,79
    ADC A,B
    SBC A,A
    AND 1
    RET

div_178:  ; ÷178  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,78
    ADC A,B
    SBC A,A
    AND 1
    RET

div_179:  ; ÷179  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,77
    ADC A,B
    SBC A,A
    AND 1
    RET

div_180:  ; ÷180  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,76
    ADC A,B
    SBC A,A
    AND 1
    RET

div_181:  ; ÷181  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,75
    ADC A,B
    SBC A,A
    AND 1
    RET

div_182:  ; ÷182  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,74
    ADC A,B
    SBC A,A
    AND 1
    RET

div_183:  ; ÷183  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,73
    ADC A,B
    SBC A,A
    AND 1
    RET

div_184:  ; ÷184  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,72
    ADC A,B
    SBC A,A
    AND 1
    RET

div_185:  ; ÷185  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,71
    ADC A,B
    SBC A,A
    AND 1
    RET

div_186:  ; ÷186  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,70
    ADC A,B
    SBC A,A
    AND 1
    RET

div_187:  ; ÷187  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,69
    ADC A,B
    SBC A,A
    AND 1
    RET

div_188:  ; ÷188  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,68
    ADC A,B
    SBC A,A
    AND 1
    RET

div_189:  ; ÷189  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,67
    ADC A,B
    SBC A,A
    AND 1
    RET

div_190:  ; ÷190  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,66
    ADC A,B
    SBC A,A
    AND 1
    RET

div_191:  ; ÷191  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,65
    ADC A,B
    SBC A,A
    AND 1
    RET

div_192:  ; ÷192  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,64
    ADC A,B
    SBC A,A
    AND 1
    RET

div_193:  ; ÷193  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,63
    ADC A,B
    SBC A,A
    AND 1
    RET

div_194:  ; ÷194  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,62
    ADC A,B
    SBC A,A
    AND 1
    RET

div_195:  ; ÷195  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,61
    ADC A,B
    SBC A,A
    AND 1
    RET

div_196:  ; ÷196  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,60
    ADC A,B
    SBC A,A
    AND 1
    RET

div_197:  ; ÷197  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,59
    ADC A,B
    SBC A,A
    AND 1
    RET

div_198:  ; ÷198  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,58
    ADC A,B
    SBC A,A
    AND 1
    RET

div_199:  ; ÷199  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,57
    ADC A,B
    SBC A,A
    AND 1
    RET

div_200:  ; ÷200  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,56
    ADC A,B
    SBC A,A
    AND 1
    RET

div_201:  ; ÷201  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,55
    ADC A,B
    SBC A,A
    AND 1
    RET

div_202:  ; ÷202  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,54
    ADC A,B
    SBC A,A
    AND 1
    RET

div_203:  ; ÷203  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,53
    ADC A,B
    SBC A,A
    AND 1
    RET

div_204:  ; ÷204  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,52
    ADC A,B
    SBC A,A
    AND 1
    RET

div_205:  ; ÷205  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,51
    ADC A,B
    SBC A,A
    AND 1
    RET

div_206:  ; ÷206  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,50
    ADC A,B
    SBC A,A
    AND 1
    RET

div_207:  ; ÷207  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,49
    ADC A,B
    SBC A,A
    AND 1
    RET

div_208:  ; ÷208  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,48
    ADC A,B
    SBC A,A
    AND 1
    RET

div_209:  ; ÷209  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,47
    ADC A,B
    SBC A,A
    AND 1
    RET

div_210:  ; ÷210  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,46
    ADC A,B
    SBC A,A
    AND 1
    RET

div_211:  ; ÷211  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,45
    ADC A,B
    SBC A,A
    AND 1
    RET

div_212:  ; ÷212  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,44
    ADC A,B
    SBC A,A
    AND 1
    RET

div_213:  ; ÷213  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,43
    ADC A,B
    SBC A,A
    AND 1
    RET

div_214:  ; ÷214  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,42
    ADC A,B
    SBC A,A
    AND 1
    RET

div_215:  ; ÷215  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,41
    ADC A,B
    SBC A,A
    AND 1
    RET

div_216:  ; ÷216  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,40
    ADC A,B
    SBC A,A
    AND 1
    RET

div_217:  ; ÷217  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,39
    ADC A,B
    SBC A,A
    AND 1
    RET

div_218:  ; ÷218  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,38
    ADC A,B
    SBC A,A
    AND 1
    RET

div_219:  ; ÷219  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,37
    ADC A,B
    SBC A,A
    AND 1
    RET

div_220:  ; ÷220  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,36
    ADC A,B
    SBC A,A
    AND 1
    RET

div_221:  ; ÷221  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,35
    ADC A,B
    SBC A,A
    AND 1
    RET

div_222:  ; ÷222  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,34
    ADC A,B
    SBC A,A
    AND 1
    RET

div_223:  ; ÷223  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,33
    ADC A,B
    SBC A,A
    AND 1
    RET

div_224:  ; ÷224  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,32
    ADC A,B
    SBC A,A
    AND 1
    RET

div_225:  ; ÷225  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,31
    ADC A,B
    SBC A,A
    AND 1
    RET

div_226:  ; ÷226  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,30
    ADC A,B
    SBC A,A
    AND 1
    RET

div_227:  ; ÷227  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,29
    ADC A,B
    SBC A,A
    AND 1
    RET

div_228:  ; ÷228  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,28
    ADC A,B
    SBC A,A
    AND 1
    RET

div_229:  ; ÷229  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,27
    ADC A,B
    SBC A,A
    AND 1
    RET

div_230:  ; ÷230  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,26
    ADC A,B
    SBC A,A
    AND 1
    RET

div_231:  ; ÷231  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,25
    ADC A,B
    SBC A,A
    AND 1
    RET

div_232:  ; ÷232  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,24
    ADC A,B
    SBC A,A
    AND 1
    RET

div_233:  ; ÷233  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,23
    ADC A,B
    SBC A,A
    AND 1
    RET

div_234:  ; ÷234  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,22
    ADC A,B
    SBC A,A
    AND 1
    RET

div_235:  ; ÷235  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,21
    ADC A,B
    SBC A,A
    AND 1
    RET

div_236:  ; ÷236  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,20
    ADC A,B
    SBC A,A
    AND 1
    RET

div_237:  ; ÷237  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,19
    ADC A,B
    SBC A,A
    AND 1
    RET

div_238:  ; ÷238  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,18
    ADC A,B
    SBC A,A
    AND 1
    RET

div_239:  ; ÷239  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,17
    ADC A,B
    SBC A,A
    AND 1
    RET

div_240:  ; ÷240  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,16
    ADC A,B
    SBC A,A
    AND 1
    RET

div_241:  ; ÷241  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,15
    ADC A,B
    SBC A,A
    AND 1
    RET

div_242:  ; ÷242  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,14
    ADC A,B
    SBC A,A
    AND 1
    RET

div_243:  ; ÷243  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,13
    ADC A,B
    SBC A,A
    AND 1
    RET

div_244:  ; ÷244  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,12
    ADC A,B
    SBC A,A
    AND 1
    RET

div_245:  ; ÷245  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,11
    ADC A,B
    SBC A,A
    AND 1
    RET

div_246:  ; ÷246  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,10
    ADC A,B
    SBC A,A
    AND 1
    RET

div_247:  ; ÷247  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,9
    ADC A,B
    SBC A,A
    AND 1
    RET

div_248:  ; ÷248  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,8
    ADC A,B
    SBC A,A
    AND 1
    RET

div_249:  ; ÷249  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,7
    ADC A,B
    SBC A,A
    AND 1
    RET

div_250:  ; ÷250  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,6
    ADC A,B
    SBC A,A
    AND 1
    RET

div_251:  ; ÷251  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,5
    ADC A,B
    SBC A,A
    AND 1
    RET

div_252:  ; ÷252  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,4
    ADC A,B
    SBC A,A
    AND 1
    RET

div_253:  ; ÷253  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,3
    ADC A,B
    SBC A,A
    AND 1
    RET

div_254:  ; ÷254  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,2
    ADC A,B
    SBC A,A
    AND 1
    RET

div_255:  ; ÷255  (5 insts, 26T | clobbers: A, B, F)
    OR A
    LD B,1
    ADC A,B
    SBC A,A
    AND 1
    RET

