; Z80 Optimal Constant Multiply Library (16-bit: HL × K → HL)
; Generated by scripts/gen_mul16_library.py from mulopt16_complete.json
; (GPU brute-force, provably optimal sequences)
;
; 254 constants (k=2..255), sequences in CORRECT execution order.
; 118 fall-through chains (genuine suffix relationships only).
;
; Convention:
;   Input:  HL = value (H=0, L=A, i.e. 8-bit value zero-extended)
;           A  = L (low byte, for initial LD C,A save)
;           B  = 0 (implicit zero high byte of BC for ADD HL,BC)
;   Output: HL = HL * K  (mod 65536)
;   Clobber: C, F  (B remains 0)
;
; Usage:
;   LD A, value      ; 8-bit value to multiply
;   LD L, A
;   LD H, 0
;   CALL mul16_42
;   ; HL = value * 42
;
; Note: even-k sequences end with ADD HL,HL, enabling 123 doubling chains:
;   mul16_192 → mul16_96 → mul16_48 → ... → mul16_3 (×3 family)
;   mul16_128 → mul16_64 → mul16_32 → ... → mul16_2 (powers of 2)
;
; Repository: https://github.com/oisee/z80-optimizer
; License: MIT
;
; --- Chain: ×128 → ×64 → ×32 → ×16 → ×8 → ×4 → ×2 ---
mul16_128:  ; ×128  (7 insts, 77T)
    ADD HL,HL
mul16_64:  ; ×64  (6 insts, 66T)
    ADD HL,HL
mul16_32:  ; ×32  (5 insts, 55T)
    ADD HL,HL
mul16_16:  ; ×16  (4 insts, 44T)
    ADD HL,HL
mul16_8:  ; ×8  (3 insts, 33T)
    ADD HL,HL
mul16_4:  ; ×4  (2 insts, 22T)
    ADD HL,HL
mul16_2:  ; ×2  (1 insts, 11T)
    ADD HL,HL
    RET

mul16_192:  ; ×192  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    JP mul16_64

mul16_96:  ; ×96  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    JP mul16_32

mul16_160:  ; ×160  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_32

mul16_224:  ; ×224  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_32

mul16_48:  ; ×48  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    JP mul16_16

mul16_80:  ; ×80  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_16

mul16_112:  ; ×112  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_16

mul16_144:  ; ×144  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_16

mul16_176:  ; ×176  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_16

mul16_208:  ; ×208  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_16

mul16_240:  ; ×240  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_16

mul16_24:  ; ×24  (6 insts, 59T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    JP mul16_8

mul16_40:  ; ×40  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_56:  ; ×56  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_72:  ; ×72  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_88:  ; ×88  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_104:  ; ×104  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_120:  ; ×120  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_8

mul16_136:  ; ×136  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_152:  ; ×152  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_168:  ; ×168  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_184:  ; ×184  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_8

mul16_200:  ; ×200  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_216:  ; ×216  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_232:  ; ×232  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_8

mul16_248:  ; ×248  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_8

mul16_12:  ; ×12  (5 insts, 48T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    JP mul16_4

mul16_20:  ; ×20  (6 insts, 59T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_28:  ; ×28  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_36:  ; ×36  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_44:  ; ×44  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_52:  ; ×52  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_60:  ; ×60  (8 insts, 85T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_68:  ; ×68  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_76:  ; ×76  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_84:  ; ×84  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_92:  ; ×92  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_100:  ; ×100  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_108:  ; ×108  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_116:  ; ×116  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_124:  ; ×124  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_132:  ; ×132  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_140:  ; ×140  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_148:  ; ×148  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_156:  ; ×156  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_164:  ; ×164  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_172:  ; ×172  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_180:  ; ×180  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_188:  ; ×188  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_196:  ; ×196  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_204:  ; ×204  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_212:  ; ×212  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_220:  ; ×220  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_228:  ; ×228  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_236:  ; ×236  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_4

mul16_244:  ; ×244  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_4

mul16_6:  ; ×6  (4 insts, 37T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    JP mul16_2

mul16_10:  ; ×10  (5 insts, 48T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_14:  ; ×14  (6 insts, 59T)
    LD C,A
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_18:  ; ×18  (6 insts, 59T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_22:  ; ×22  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_26:  ; ×26  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_30:  ; ×30  (7 insts, 74T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_34:  ; ×34  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_38:  ; ×38  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_42:  ; ×42  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_46:  ; ×46  (8 insts, 85T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_50:  ; ×50  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_54:  ; ×54  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_58:  ; ×58  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_62:  ; ×62  (8 insts, 85T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_66:  ; ×66  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_70:  ; ×70  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_74:  ; ×74  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_78:  ; ×78  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_82:  ; ×82  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_86:  ; ×86  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_90:  ; ×90  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_94:  ; ×94  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_98:  ; ×98  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_102:  ; ×102  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_106:  ; ×106  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_110:  ; ×110  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_114:  ; ×114  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_118:  ; ×118  (10 insts, 111T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_122:  ; ×122  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_126:  ; ×126  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_130:  ; ×130  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_134:  ; ×134  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_138:  ; ×138  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_142:  ; ×142  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_146:  ; ×146  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_150:  ; ×150  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_154:  ; ×154  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_158:  ; ×158  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_162:  ; ×162  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_166:  ; ×166  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_170:  ; ×170  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_174:  ; ×174  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_178:  ; ×178  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_182:  ; ×182  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_186:  ; ×186  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_190:  ; ×190  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_194:  ; ×194  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_198:  ; ×198  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_202:  ; ×202  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_206:  ; ×206  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_210:  ; ×210  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_214:  ; ×214  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_218:  ; ×218  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_222:  ; ×222  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_226:  ; ×226  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_230:  ; ×230  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_234:  ; ×234  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_238:  ; ×238  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_242:  ; ×242  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    JP mul16_2

mul16_246:  ; ×246  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    JP mul16_2

mul16_3:  ; ×3  (3 insts, 26T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    RET

mul16_5:  ; ×5  (4 insts, 37T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_7:  ; ×7  (5 insts, 48T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_9:  ; ×9  (5 insts, 48T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_11:  ; ×11  (6 insts, 59T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_13:  ; ×13  (6 insts, 59T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_15:  ; ×15  (6 insts, 63T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_17:  ; ×17  (6 insts, 59T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_19:  ; ×19  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_21:  ; ×21  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_23:  ; ×23  (7 insts, 74T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_25:  ; ×25  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_27:  ; ×27  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_29:  ; ×29  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_31:  ; ×31  (7 insts, 74T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_33:  ; ×33  (7 insts, 70T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_35:  ; ×35  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_37:  ; ×37  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_39:  ; ×39  (8 insts, 85T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_41:  ; ×41  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_43:  ; ×43  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_45:  ; ×45  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_47:  ; ×47  (8 insts, 85T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_49:  ; ×49  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_51:  ; ×51  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_53:  ; ×53  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_55:  ; ×55  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_57:  ; ×57  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_59:  ; ×59  (9 insts, 100T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_61:  ; ×61  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_63:  ; ×63  (8 insts, 85T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_65:  ; ×65  (8 insts, 81T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_67:  ; ×67  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_69:  ; ×69  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_71:  ; ×71  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_73:  ; ×73  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_75:  ; ×75  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_77:  ; ×77  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_79:  ; ×79  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_81:  ; ×81  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_83:  ; ×83  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_85:  ; ×85  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_87:  ; ×87  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_89:  ; ×89  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_91:  ; ×91  (10 insts, 111T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_93:  ; ×93  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_95:  ; ×95  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_97:  ; ×97  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_99:  ; ×99  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_101:  ; ×101  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_103:  ; ×103  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_105:  ; ×105  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_107:  ; ×107  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_109:  ; ×109  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_111:  ; ×111  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_113:  ; ×113  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_115:  ; ×115  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_117:  ; ×117  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_119:  ; ×119  (10 insts, 111T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_121:  ; ×121  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_123:  ; ×123  (10 insts, 111T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_125:  ; ×125  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_127:  ; ×127  (9 insts, 96T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_129:  ; ×129  (9 insts, 92T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_131:  ; ×131  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_133:  ; ×133  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_135:  ; ×135  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_137:  ; ×137  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_139:  ; ×139  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_141:  ; ×141  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_143:  ; ×143  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_145:  ; ×145  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_147:  ; ×147  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_149:  ; ×149  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_151:  ; ×151  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_153:  ; ×153  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_155:  ; ×155  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_157:  ; ×157  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_159:  ; ×159  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_161:  ; ×161  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_163:  ; ×163  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_165:  ; ×165  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_167:  ; ×167  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_169:  ; ×169  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_171:  ; ×171  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_173:  ; ×173  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_175:  ; ×175  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_177:  ; ×177  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_179:  ; ×179  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_181:  ; ×181  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_183:  ; ×183  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_185:  ; ×185  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_187:  ; ×187  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_189:  ; ×189  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_191:  ; ×191  (10 insts, 107T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_193:  ; ×193  (10 insts, 103T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_195:  ; ×195  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_197:  ; ×197  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_199:  ; ×199  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_201:  ; ×201  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_203:  ; ×203  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_205:  ; ×205  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_207:  ; ×207  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_209:  ; ×209  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_211:  ; ×211  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_213:  ; ×213  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_215:  ; ×215  (12 insts, 129T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_217:  ; ×217  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_219:  ; ×219  (12 insts, 133T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_221:  ; ×221  (12 insts, 129T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_223:  ; ×223  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_225:  ; ×225  (11 insts, 114T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_227:  ; ×227  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_229:  ; ×229  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_231:  ; ×231  (12 insts, 129T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_233:  ; ×233  (12 insts, 125T)
    LD C,A
    ADD HL,BC
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_235:  ; ×235  (12 insts, 137T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_237:  ; ×237  (12 insts, 133T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_239:  ; ×239  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_241:  ; ×241  (11 insts, 118T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_243:  ; ×243  (12 insts, 129T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,BC
    RET

mul16_245:  ; ×245  (12 insts, 129T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,BC
    RET

mul16_247:  ; ×247  (11 insts, 122T)
    LD C,A
    ADD HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    ADD HL,HL
    ADD HL,HL
    ADD HL,HL
    OR A
    SBC HL,BC
    RET

mul16_249:  ; ×249  (9 insts, 120T)
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    RET

mul16_250:  ; ×250  (8 insts, 105T)
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    RET

mul16_251:  ; ×251  (7 insts, 90T)
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    RET

mul16_252:  ; ×252  (6 insts, 75T)
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    RET

mul16_253:  ; ×253  (5 insts, 60T)
    LD C,A
    LD A,L
    LD L,H
    LD H,A
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    RET

mul16_254:  ; ×254  (4 insts, 45T)
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    OR A
    SBC HL,BC
    OR A
    SBC HL,BC
    RET

mul16_255:  ; ×255  (3 insts, 30T)
    LD A,L
    LD L,H
    LD H,A
    LD C,A
    OR A
    SBC HL,BC
    RET

