; Z80 Optimal Constant Multiply Library (8-bit: A × K → A mod 256)
; Generated by scripts/gen_mul8_library.py
; Sources: mulopt8_clobber.json (GPU brute-force) + chains_mul8_mod256.json (abstract chains)
;
; 254 constants (k=2..255), sequences in CORRECT execution order.
; 77 fall-through chains (genuine suffix relationships only).
; 139 entries use abstract-chain translation (carry-independent, enables doubling chains).
;
; Input:  A = value to multiply
; Output: A = A * K (mod 256)
; Clobber: B (for most), F always
;
; Usage:  LD A, (value)
;         CALL mul_42
;         ; A now contains value * 42
;
; Note: abstract-chain sequences (LD B,A / ADD A,A / ADD A,B / SUB B only) are
; carry-independent and form doubling families: mul_56→mul_28→mul_14→mul_7, etc.
; GPU-optimal sequences (using ADC/SBC/RLA/RLCA/NEG) may be a few T-states
; better for isolated calls but cannot chain.
;
; Repository: https://github.com/oisee/z80-optimizer
; License: MIT
;
; --- Chain: ×192 → ×64 → ×32 → ×16 → ×8 → ×4 → ×2 ---
mul_192:  ; ×192  (7 insts, 32T)
    NEG
mul_64:  ; ×64  (6 insts, 24T [abstract])
    ADD A,A
mul_32:  ; ×32  (5 insts, 20T [abstract])
    ADD A,A
mul_16:  ; ×16  (4 insts, 16T [abstract])
    ADD A,A
mul_8:  ; ×8  (3 insts, 12T [abstract])
    ADD A,A
mul_4:  ; ×4  (2 insts, 8T [abstract])
    ADD A,A
mul_2:  ; ×2  (1 insts, 4T [abstract])
    ADD A,A
    RET

; --- Chain: ×96 → ×48 → ×24 → ×12 → ×6 → ×3 ---
mul_96:  ; ×96  (8 insts, 32T [abstract])
    ADD A,A
mul_48:  ; ×48  (7 insts, 28T [abstract])
    ADD A,A
mul_24:  ; ×24  (6 insts, 24T [abstract])
    ADD A,A
mul_12:  ; ×12  (5 insts, 20T [abstract])
    ADD A,A
mul_6:  ; ×6  (4 insts, 16T [abstract])
    ADD A,A
mul_3:  ; ×3  (3 insts, 12T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×160 → ×80 → ×40 → ×20 → ×10 → ×5 ---
mul_160:  ; ×160  (9 insts, 36T [abstract])
    ADD A,A
mul_80:  ; ×80  (8 insts, 32T [abstract])
    ADD A,A
mul_40:  ; ×40  (7 insts, 28T [abstract])
    ADD A,A
mul_20:  ; ×20  (6 insts, 24T [abstract])
    ADD A,A
mul_10:  ; ×10  (5 insts, 20T [abstract])
    ADD A,A
mul_5:  ; ×5  (4 insts, 16T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_224:  ; ×224  (6 insts, 28T)
    NEG
    JP mul_32

; --- Chain: ×112 → ×56 → ×28 → ×14 → ×7 ---
mul_112:  ; ×112  (9 insts, 36T [abstract])
    ADD A,A
mul_56:  ; ×56  (8 insts, 32T [abstract])
    ADD A,A
mul_28:  ; ×28  (7 insts, 28T [abstract])
    ADD A,A
mul_14:  ; ×14  (6 insts, 24T [abstract])
    ADD A,A
mul_7:  ; ×7  (5 insts, 20T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×144 → ×72 → ×36 → ×18 → ×9 ---
mul_144:  ; ×144  (9 insts, 36T [abstract])
    ADD A,A
mul_72:  ; ×72  (8 insts, 32T [abstract])
    ADD A,A
mul_36:  ; ×36  (7 insts, 28T [abstract])
    ADD A,A
mul_18:  ; ×18  (6 insts, 24T [abstract])
    ADD A,A
mul_9:  ; ×9  (5 insts, 20T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_176:  ; ×176  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    JP mul_16

mul_208:  ; ×208  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    JP mul_16

; --- Chain: ×88 → ×44 → ×22 → ×11 ---
mul_88:  ; ×88  (9 insts, 36T [abstract])
    ADD A,A
mul_44:  ; ×44  (8 insts, 32T [abstract])
    ADD A,A
mul_22:  ; ×22  (7 insts, 28T [abstract])
    ADD A,A
mul_11:  ; ×11  (6 insts, 24T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×104 → ×52 → ×26 → ×13 ---
mul_104:  ; ×104  (9 insts, 36T [abstract])
    ADD A,A
mul_52:  ; ×52  (8 insts, 32T [abstract])
    ADD A,A
mul_26:  ; ×26  (7 insts, 28T [abstract])
    ADD A,A
mul_13:  ; ×13  (6 insts, 24T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×120 → ×60 → ×30 → ×15 ---
mul_120:  ; ×120  (9 insts, 36T [abstract])
    ADD A,A
mul_60:  ; ×60  (8 insts, 32T [abstract])
    ADD A,A
mul_30:  ; ×30  (7 insts, 28T [abstract])
    ADD A,A
mul_15:  ; ×15  (6 insts, 24T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×136 → ×68 → ×34 → ×17 ---
mul_136:  ; ×136  (9 insts, 36T [abstract])
    ADD A,A
mul_68:  ; ×68  (8 insts, 32T [abstract])
    ADD A,A
mul_34:  ; ×34  (7 insts, 28T [abstract])
    ADD A,A
mul_17:  ; ×17  (6 insts, 24T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×152 → ×76 → ×38 → ×19 ---
mul_152:  ; ×152  (10 insts, 40T [abstract])
    ADD A,A
mul_76:  ; ×76  (9 insts, 36T [abstract])
    ADD A,A
mul_38:  ; ×38  (8 insts, 32T [abstract])
    ADD A,A
mul_19:  ; ×19  (7 insts, 28T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×168 → ×84 → ×42 → ×21 ---
mul_168:  ; ×168  (10 insts, 40T [abstract])
    ADD A,A
mul_84:  ; ×84  (9 insts, 36T [abstract])
    ADD A,A
mul_42:  ; ×42  (8 insts, 32T [abstract])
    ADD A,A
mul_21:  ; ×21  (7 insts, 28T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_184:  ; ×184  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_8

mul_200:  ; ×200  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    JP mul_8

mul_216:  ; ×216  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    JP mul_8

mul_232:  ; ×232  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    JP mul_8

; --- Chain: ×92 → ×46 → ×23 ---
mul_92:  ; ×92  (9 insts, 36T [abstract])
    ADD A,A
mul_46:  ; ×46  (8 insts, 32T [abstract])
    ADD A,A
mul_23:  ; ×23  (7 insts, 28T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×100 → ×50 → ×25 ---
mul_100:  ; ×100  (9 insts, 36T [abstract])
    ADD A,A
mul_50:  ; ×50  (8 insts, 32T [abstract])
    ADD A,A
mul_25:  ; ×25  (7 insts, 28T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×116 → ×58 → ×29 ---
mul_116:  ; ×116  (10 insts, 40T [abstract])
    ADD A,A
mul_58:  ; ×58  (9 insts, 36T [abstract])
    ADD A,A
mul_29:  ; ×29  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    SUB B
    RET

; --- Chain: ×124 → ×62 → ×31 ---
mul_124:  ; ×124  (9 insts, 36T [abstract])
    ADD A,A
mul_62:  ; ×62  (8 insts, 32T [abstract])
    ADD A,A
mul_31:  ; ×31  (7 insts, 28T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×132 → ×66 → ×33 ---
mul_132:  ; ×132  (9 insts, 36T [abstract])
    ADD A,A
mul_66:  ; ×66  (8 insts, 32T [abstract])
    ADD A,A
mul_33:  ; ×33  (7 insts, 28T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×140 → ×70 → ×35 ---
mul_140:  ; ×140  (10 insts, 40T [abstract])
    ADD A,A
mul_70:  ; ×70  (9 insts, 36T [abstract])
    ADD A,A
mul_35:  ; ×35  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×148 → ×74 → ×37 ---
mul_148:  ; ×148  (10 insts, 40T [abstract])
    ADD A,A
mul_74:  ; ×74  (9 insts, 36T [abstract])
    ADD A,A
mul_37:  ; ×37  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×156 → ×78 → ×39 ---
mul_156:  ; ×156  (10 insts, 40T [abstract])
    ADD A,A
mul_78:  ; ×78  (9 insts, 36T [abstract])
    ADD A,A
mul_39:  ; ×39  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×164 → ×82 → ×41 ---
mul_164:  ; ×164  (10 insts, 40T [abstract])
    ADD A,A
mul_82:  ; ×82  (9 insts, 36T [abstract])
    ADD A,A
mul_41:  ; ×41  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_172:  ; ×172  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_4

mul_180:  ; ×180  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    JP mul_4

mul_188:  ; ×188  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_4

mul_196:  ; ×196  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    JP mul_4

mul_204:  ; ×204  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_4

mul_212:  ; ×212  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    JP mul_4

mul_220:  ; ×220  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_4

mul_228:  ; ×228  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    SUB B
    JP mul_4

mul_236:  ; ×236  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    JP mul_4

mul_244:  ; ×244  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    JP mul_4

mul_248:  ; ×248  (4 insts, 20T)
    RLA
    NEG
    JP mul_4

; --- Chain: ×86 → ×43 ---
mul_86:  ; ×86  (10 insts, 40T [abstract])
    ADD A,A
mul_43:  ; ×43  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×94 → ×47 ---
mul_94:  ; ×94  (9 insts, 36T [abstract])
    ADD A,A
mul_47:  ; ×47  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×98 → ×49 ---
mul_98:  ; ×98  (9 insts, 36T [abstract])
    ADD A,A
mul_49:  ; ×49  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×106 → ×53 ---
mul_106:  ; ×106  (10 insts, 40T [abstract])
    ADD A,A
mul_53:  ; ×53  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_108:  ; ×108  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

; --- Chain: ×110 → ×55 ---
mul_110:  ; ×110  (10 insts, 40T [abstract])
    ADD A,A
mul_55:  ; ×55  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×114 → ×57 ---
mul_114:  ; ×114  (10 insts, 40T [abstract])
    ADD A,A
mul_57:  ; ×57  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×118 → ×59 ---
mul_118:  ; ×118  (10 insts, 40T [abstract])
    ADD A,A
mul_59:  ; ×59  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×122 → ×61 ---
mul_122:  ; ×122  (10 insts, 40T [abstract])
    ADD A,A
mul_61:  ; ×61  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    SUB B
    RET

; --- Chain: ×134 → ×67 ---
mul_134:  ; ×134  (10 insts, 40T [abstract])
    ADD A,A
mul_67:  ; ×67  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×138 → ×69 ---
mul_138:  ; ×138  (10 insts, 40T [abstract])
    ADD A,A
mul_69:  ; ×69  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×142 → ×71 ---
mul_142:  ; ×142  (10 insts, 40T [abstract])
    ADD A,A
mul_71:  ; ×71  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×146 → ×73 ---
mul_146:  ; ×146  (10 insts, 40T [abstract])
    ADD A,A
mul_73:  ; ×73  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

; --- Chain: ×158 → ×79 ---
mul_158:  ; ×158  (10 insts, 40T [abstract])
    ADD A,A
mul_79:  ; ×79  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

; --- Chain: ×162 → ×81 ---
mul_162:  ; ×162  (10 insts, 40T [abstract])
    ADD A,A
mul_81:  ; ×81  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_174:  ; ×174  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_178:  ; ×178  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_182:  ; ×182  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_186:  ; ×186  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_190:  ; ×190  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_194:  ; ×194  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_198:  ; ×198  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_202:  ; ×202  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_206:  ; ×206  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_210:  ; ×210  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_211:  ; ×211  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    JP mul_15

mul_214:  ; ×214  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_218:  ; ×218  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_222:  ; ×222  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_226:  ; ×226  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_230:  ; ×230  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_234:  ; ×234  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    JP mul_2

mul_238:  ; ×238  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_239:  ; ×239  (7 insts, 32T)
    NEG
    JP mul_17

; --- Chain: ×240 → ×255 ---
mul_240:  ; ×240  (5 insts, 24T)
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
mul_255:  ; ×255  (1 insts, 8T)
    NEG
    RET

mul_242:  ; ×242  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    JP mul_2

mul_246:  ; ×246  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    JP mul_2

mul_252:  ; ×252  (3 insts, 16T)
    RLA
    NEG
    JP mul_2

mul_254:  ; ×254  (2 insts, 12T)
    RLA
    JP mul_255

mul_27:  ; ×27  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_45:  ; ×45  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_51:  ; ×51  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_54:  ; ×54  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_63:  ; ×63  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_65:  ; ×65  (8 insts, 32T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_75:  ; ×75  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_77:  ; ×77  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_83:  ; ×83  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_85:  ; ×85  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_87:  ; ×87  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_89:  ; ×89  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_90:  ; ×90  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_91:  ; ×91  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_93:  ; ×93  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_95:  ; ×95  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_97:  ; ×97  (9 insts, 36T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_99:  ; ×99  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_101:  ; ×101  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_102:  ; ×102  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_103:  ; ×103  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_105:  ; ×105  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_107:  ; ×107  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_109:  ; ×109  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_111:  ; ×111  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_113:  ; ×113  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_115:  ; ×115  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_117:  ; ×117  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    SUB B
    RET

mul_119:  ; ×119  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_121:  ; ×121  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_123:  ; ×123  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_125:  ; ×125  (8 insts, 36T)
    LD B,A
    RRCA
    SBC A,A
    NEG
    RRA
    SUB B
    SUB B
    SUB B
    RET

mul_126:  ; ×126  (7 insts, 32T)
    RRCA
    ADD A,A
    LD B,A
    SBC A,A
    SRL A
    SBC A,B
    SUB B
    RET

mul_127:  ; ×127  (6 insts, 28T)
    RRCA
    LD B,A
    ADC A,B
    NEG
    RRA
    SUB B
    RET

mul_128:  ; ×128  (4 insts, 16T)
    RRCA
    SBC A,A
    ADC A,B
    RRA
    RET

mul_129:  ; ×129  (5 insts, 20T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    RET

mul_130:  ; ×130  (6 insts, 28T)
    LD B,A
    RRCA
    SBC A,A
    SRL A
    ADC A,B
    ADD A,B
    RET

mul_131:  ; ×131  (7 insts, 32T)
    LD B,A
    RRCA
    SBC A,A
    SRL A
    ADC A,B
    ADD A,B
    ADD A,B
    RET

mul_133:  ; ×133  (9 insts, 36T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_135:  ; ×135  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_137:  ; ×137  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_139:  ; ×139  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_141:  ; ×141  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_143:  ; ×143  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_145:  ; ×145  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_147:  ; ×147  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_149:  ; ×149  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_150:  ; ×150  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_151:  ; ×151  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_153:  ; ×153  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_154:  ; ×154  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_155:  ; ×155  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_157:  ; ×157  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_159:  ; ×159  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_161:  ; ×161  (10 insts, 40T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_163:  ; ×163  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_165:  ; ×165  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_166:  ; ×166  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_167:  ; ×167  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_169:  ; ×169  (11 insts, 44T [abstract])
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_170:  ; ×170  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_171:  ; ×171  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_173:  ; ×173  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_175:  ; ×175  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_177:  ; ×177  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_179:  ; ×179  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_181:  ; ×181  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_183:  ; ×183  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_185:  ; ×185  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_187:  ; ×187  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_189:  ; ×189  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_191:  ; ×191  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_193:  ; ×193  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_195:  ; ×195  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_197:  ; ×197  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_199:  ; ×199  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_201:  ; ×201  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_203:  ; ×203  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_205:  ; ×205  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_207:  ; ×207  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_209:  ; ×209  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_213:  ; ×213  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_215:  ; ×215  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_217:  ; ×217  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_219:  ; ×219  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_221:  ; ×221  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_223:  ; ×223  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_225:  ; ×225  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_227:  ; ×227  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_229:  ; ×229  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_231:  ; ×231  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_233:  ; ×233  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_235:  ; ×235  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_237:  ; ×237  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_241:  ; ×241  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_243:  ; ×243  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_245:  ; ×245  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_247:  ; ×247  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_249:  ; ×249  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_250:  ; ×250  (5 insts, 24T)
    RLA
    LD B,A
    NEG
    RLCA
    SBC A,B
    RET

mul_251:  ; ×251  (5 insts, 24T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_253:  ; ×253  (4 insts, 20T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    RET

