; Z80 Optimal Constant Multiply Library
; Generated by scripts/gen_mul8_library.py from mulopt8_clobber.json
; (GPU brute-force, provably optimal sequences)
;
; 254 constants (k=2..255), sequences in CORRECT execution order.
; 1 fall-through chains (genuine suffix relationships only).
;
; Input:  A = value to multiply
; Output: A = A * K (mod 256)
; Clobber: B (for most), F always
;
; Usage:  LD A, (value)
;         CALL mul_42
;         ; A now contains value * 42
;
; Repository: https://github.com/oisee/z80-optimizer
; License: MIT
;
; --- Chain: ×240 → ×254 → ×255 ---
mul_240:  ; ×240  (5 insts, 24T)
    RLA
    ADD A,A
    ADD A,A
mul_254:  ; ×254  (2 insts, 12T)
    RLA
mul_255:  ; ×255  (1 insts, 8T)
    NEG
    RET

mul_2:  ; ×2  (1 insts, 4T)
    RLA
    RET

mul_3:  ; ×3  (3 insts, 12T)
    LD B,A
    ADC A,A
    ADD A,B
    RET

mul_4:  ; ×4  (2 insts, 8T)
    RLA
    ADD A,A
    RET

mul_5:  ; ×5  (4 insts, 16T)
    LD B,A
    ADC A,B
    ADD A,A
    ADD A,B
    RET

mul_6:  ; ×6  (4 insts, 16T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    RET

mul_7:  ; ×7  (5 insts, 20T)
    LD B,A
    ADC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_8:  ; ×8  (3 insts, 12T)
    RLA
    ADD A,A
    ADD A,A
    RET

mul_9:  ; ×9  (5 insts, 20T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_10:  ; ×10  (5 insts, 20T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_11:  ; ×11  (6 insts, 24T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_12:  ; ×12  (5 insts, 20T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RET

mul_13:  ; ×13  (6 insts, 24T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_14:  ; ×14  (6 insts, 24T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_15:  ; ×15  (6 insts, 24T)
    LD B,A
    ADC A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_16:  ; ×16  (4 insts, 16T)
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_17:  ; ×17  (6 insts, 24T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_18:  ; ×18  (6 insts, 24T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_19:  ; ×19  (7 insts, 28T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_20:  ; ×20  (6 insts, 24T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_21:  ; ×21  (7 insts, 28T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_22:  ; ×22  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_23:  ; ×23  (7 insts, 28T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_24:  ; ×24  (6 insts, 24T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_25:  ; ×25  (7 insts, 28T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_26:  ; ×26  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_27:  ; ×27  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_28:  ; ×28  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_29:  ; ×29  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_30:  ; ×30  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_31:  ; ×31  (7 insts, 28T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_32:  ; ×32  (5 insts, 20T)
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_33:  ; ×33  (7 insts, 28T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_34:  ; ×34  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_35:  ; ×35  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_36:  ; ×36  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_37:  ; ×37  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_38:  ; ×38  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_39:  ; ×39  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_40:  ; ×40  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_41:  ; ×41  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_42:  ; ×42  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_43:  ; ×43  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_44:  ; ×44  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_45:  ; ×45  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_46:  ; ×46  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_47:  ; ×47  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_48:  ; ×48  (7 insts, 28T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_49:  ; ×49  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_50:  ; ×50  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_51:  ; ×51  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_52:  ; ×52  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_53:  ; ×53  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_54:  ; ×54  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_55:  ; ×55  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_56:  ; ×56  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_57:  ; ×57  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_58:  ; ×58  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_59:  ; ×59  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_60:  ; ×60  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_61:  ; ×61  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_62:  ; ×62  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_63:  ; ×63  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_64:  ; ×64  (6 insts, 24T)
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_65:  ; ×65  (8 insts, 32T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_66:  ; ×66  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_67:  ; ×67  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_68:  ; ×68  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_69:  ; ×69  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_70:  ; ×70  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_71:  ; ×71  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_72:  ; ×72  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_73:  ; ×73  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_74:  ; ×74  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_75:  ; ×75  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_76:  ; ×76  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_77:  ; ×77  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_78:  ; ×78  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_79:  ; ×79  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_80:  ; ×80  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_81:  ; ×81  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_82:  ; ×82  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_83:  ; ×83  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_84:  ; ×84  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_85:  ; ×85  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_86:  ; ×86  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_87:  ; ×87  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_88:  ; ×88  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_89:  ; ×89  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_90:  ; ×90  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_91:  ; ×91  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_92:  ; ×92  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_93:  ; ×93  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_94:  ; ×94  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_95:  ; ×95  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_96:  ; ×96  (8 insts, 32T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_97:  ; ×97  (9 insts, 36T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_98:  ; ×98  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_99:  ; ×99  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_100:  ; ×100  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_101:  ; ×101  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_102:  ; ×102  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_103:  ; ×103  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_104:  ; ×104  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_105:  ; ×105  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_106:  ; ×106  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_107:  ; ×107  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_108:  ; ×108  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_109:  ; ×109  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_110:  ; ×110  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_111:  ; ×111  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_112:  ; ×112  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_113:  ; ×113  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_114:  ; ×114  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_115:  ; ×115  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_116:  ; ×116  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_117:  ; ×117  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_118:  ; ×118  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_119:  ; ×119  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_120:  ; ×120  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_121:  ; ×121  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_122:  ; ×122  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_123:  ; ×123  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_124:  ; ×124  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_125:  ; ×125  (8 insts, 36T)
    LD B,A
    RRCA
    SBC A,A
    NEG
    RRA
    SUB B
    SUB B
    SUB B
    RET

mul_126:  ; ×126  (7 insts, 32T)
    RRCA
    ADD A,A
    LD B,A
    SBC A,A
    SRL A
    SBC A,B
    SUB B
    RET

mul_127:  ; ×127  (6 insts, 28T)
    RRCA
    LD B,A
    ADC A,B
    NEG
    RRA
    SUB B
    RET

mul_128:  ; ×128  (4 insts, 16T)
    RRCA
    SBC A,A
    ADC A,B
    RRA
    RET

mul_129:  ; ×129  (5 insts, 20T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    RET

mul_130:  ; ×130  (6 insts, 28T)
    LD B,A
    RRCA
    SBC A,A
    SRL A
    ADC A,B
    ADD A,B
    RET

mul_131:  ; ×131  (7 insts, 32T)
    LD B,A
    RRCA
    SBC A,A
    SRL A
    ADC A,B
    ADD A,B
    ADD A,B
    RET

mul_132:  ; ×132  (8 insts, 36T)
    RLA
    LD B,A
    RRCA
    RRCA
    SBC A,A
    SRL A
    ADC A,B
    ADD A,B
    RET

mul_133:  ; ×133  (9 insts, 36T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_134:  ; ×134  (9 insts, 40T)
    RLA
    LD B,A
    RRCA
    RRCA
    SBC A,A
    SRL A
    ADC A,B
    ADD A,B
    ADD A,B
    RET

mul_135:  ; ×135  (10 insts, 40T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_136:  ; ×136  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_137:  ; ×137  (10 insts, 40T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_138:  ; ×138  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_139:  ; ×139  (11 insts, 44T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_140:  ; ×140  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_141:  ; ×141  (11 insts, 44T)
    RRA
    LD B,A
    RLA
    RRCA
    ADC A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_142:  ; ×142  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_143:  ; ×143  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_144:  ; ×144  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_145:  ; ×145  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_146:  ; ×146  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_147:  ; ×147  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_148:  ; ×148  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_149:  ; ×149  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_150:  ; ×150  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_151:  ; ×151  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_152:  ; ×152  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_153:  ; ×153  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_154:  ; ×154  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_155:  ; ×155  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_156:  ; ×156  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_157:  ; ×157  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_158:  ; ×158  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_159:  ; ×159  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_160:  ; ×160  (9 insts, 36T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_161:  ; ×161  (10 insts, 40T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_162:  ; ×162  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_163:  ; ×163  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_164:  ; ×164  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_165:  ; ×165  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_166:  ; ×166  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_167:  ; ×167  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_168:  ; ×168  (10 insts, 40T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_169:  ; ×169  (11 insts, 44T)
    LD B,A
    RLA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_170:  ; ×170  (11 insts, 44T)
    RLA
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_171:  ; ×171  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_172:  ; ×172  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_173:  ; ×173  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_174:  ; ×174  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_175:  ; ×175  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_176:  ; ×176  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_177:  ; ×177  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_178:  ; ×178  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_179:  ; ×179  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_180:  ; ×180  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_181:  ; ×181  (11 insts, 48T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_182:  ; ×182  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_183:  ; ×183  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_184:  ; ×184  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_185:  ; ×185  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_186:  ; ×186  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_187:  ; ×187  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_188:  ; ×188  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_189:  ; ×189  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_190:  ; ×190  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_191:  ; ×191  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_192:  ; ×192  (7 insts, 32T)
    NEG
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_193:  ; ×193  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_194:  ; ×194  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_195:  ; ×195  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_196:  ; ×196  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_197:  ; ×197  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_198:  ; ×198  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_199:  ; ×199  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_200:  ; ×200  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_201:  ; ×201  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_202:  ; ×202  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_203:  ; ×203  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_204:  ; ×204  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_205:  ; ×205  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_206:  ; ×206  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_207:  ; ×207  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_208:  ; ×208  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_209:  ; ×209  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_210:  ; ×210  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_211:  ; ×211  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_212:  ; ×212  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    ADD A,A
    RET

mul_213:  ; ×213  (10 insts, 44T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_214:  ; ×214  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_215:  ; ×215  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_216:  ; ×216  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_217:  ; ×217  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_218:  ; ×218  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_219:  ; ×219  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_220:  ; ×220  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_221:  ; ×221  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_222:  ; ×222  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_223:  ; ×223  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_224:  ; ×224  (6 insts, 28T)
    NEG
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_225:  ; ×225  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_226:  ; ×226  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_227:  ; ×227  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_228:  ; ×228  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    RET

mul_229:  ; ×229  (9 insts, 40T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_230:  ; ×230  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_231:  ; ×231  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_232:  ; ×232  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RET

mul_233:  ; ×233  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SUB B
    RET

mul_234:  ; ×234  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_235:  ; ×235  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_236:  ; ×236  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_237:  ; ×237  (8 insts, 36T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_238:  ; ×238  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_239:  ; ×239  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_241:  ; ×241  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_242:  ; ×242  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    ADD A,A
    RET

mul_243:  ; ×243  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_244:  ; ×244  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    ADD A,A
    ADD A,A
    RET

mul_245:  ; ×245  (7 insts, 32T)
    NEG
    LD B,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_246:  ; ×246  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RET

mul_247:  ; ×247  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RET

mul_248:  ; ×248  (4 insts, 20T)
    RLA
    NEG
    ADD A,A
    ADD A,A
    RET

mul_249:  ; ×249  (6 insts, 28T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    RLCA
    SBC A,B
    RET

mul_250:  ; ×250  (5 insts, 24T)
    RLA
    LD B,A
    NEG
    RLCA
    SBC A,B
    RET

mul_251:  ; ×251  (5 insts, 24T)
    NEG
    LD B,A
    ADD A,B
    ADD A,A
    ADD A,B
    RET

mul_252:  ; ×252  (3 insts, 16T)
    RLA
    NEG
    ADD A,A
    RET

mul_253:  ; ×253  (4 insts, 20T)
    NEG
    LD B,A
    ADD A,B
    ADD A,B
    RET

