; Z80 Optimal Constant Multiply Library (packed)
; Generated by z80-optimizer (GPU brute-force, provably optimal)
;
; 254 constants (k=2..255), 1634 instructions emitted
; 66 fall-through chains, 94 standalone entries
; Compression ratio: 1.47x (2402 flat -> 1634 packed)
;
; Input: A = value to multiply
; Output: A = A * K (mod 256)
; Clobber: B (for most), F always
;
; Usage: LD A, (value)
;        CALL mul_42
;        ; A now contains value * 42
;
; Repository: https://github.com/oisee/z80-optimizer
; License: MIT
;

; --- Chain: ×54 → ×14 ---
mul_54:
    SBC A,B
    RLCA
    ADD A,A
mul_14:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×58 → ×56 ---
mul_58:
    ADD A,B
mul_56:
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×64 → ×32 → ×16 → ×8 → ×4 ---
mul_64:
    ADD A,A
mul_32:
    ADD A,A
mul_16:
    ADD A,A
mul_8:
    ADD A,A
mul_4:
    ADD A,A
    RLA
    RET

; --- Chain: ×67 → ×33 ---
mul_67:
    ADD A,B
    ADD A,A
mul_33:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×69 → ×17 ---
mul_69:
    ADD A,B
    ADD A,A
    ADD A,A
mul_17:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×86 → ×44 ---
mul_86:
    SBC A,B
    RLCA
mul_44:
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×87 → ×11 ---
mul_87:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
mul_11:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

; --- Chain: ×91 → ×23 ---
mul_91:
    SBC A,B
    RLCA
    ADD A,A
mul_23:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

; --- Chain: ×92 → ×46 → ×24 ---
mul_92:
    ADD A,A
mul_46:
    SBC A,B
    RLCA
mul_24:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×94 → ×48 ---
mul_94:
    SBC A,B
    RLCA
mul_48:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×98 → ×96 ---
mul_98:
    ADD A,B
mul_96:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×100 → ×50 ---
mul_100:
    ADD A,A
mul_50:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×101 → ×25 ---
mul_101:
    ADD A,B
    ADD A,A
    ADD A,A
mul_25:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

; --- Chain: ×103 → ×13 ---
mul_103:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
mul_13:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

; --- Chain: ×106 → ×104 → ×52 → ×26 ---
mul_106:
    ADD A,B
mul_104:
    ADD A,A
mul_52:
    ADD A,A
mul_26:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×110 → ×12 ---
mul_110:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
mul_12:
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×118 → ×60 → ×30 ---
mul_118:
    SBC A,B
    RLCA
mul_60:
    ADD A,A
mul_30:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×122 → ×120 ---
mul_122:
    ADD A,B
mul_120:
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×123 → ×31 ---
mul_123:
    SUB B
    ADD A,A
    ADD A,A
mul_31:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×124 → ×62 → ×2 ---
mul_124:
    ADD A,A
mul_62:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
mul_2:
    RLA
    RET

; --- Chain: ×131 → ×130 ---
mul_131:
    ADD A,B
mul_130:
    ADD A,B
    ADC A,B
    SRL A
    SBC A,A
    RRCA
    LD B,A
    RET

; --- Chain: ×134 → ×132 ---
mul_134:
    ADD A,B
mul_132:
    ADD A,B
    ADC A,B
    SRL A
    SBC A,A
    RRCA
    RRCA
    LD B,A
    RLA
    RET

; --- Chain: ×138 → ×136 → ×68 → ×34 ---
mul_138:
    ADD A,B
mul_136:
    ADD A,A
mul_68:
    ADD A,A
mul_34:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×139 → ×129 ---
mul_139:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
mul_129:
    ADC A,B
    RRCA
    RLA
    LD B,A
    RRA
    RET

; --- Chain: ×140 → ×70 → ×18 ---
mul_140:
    ADD A,A
mul_70:
    SBC A,B
    RLCA
    ADD A,A
mul_18:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×142 → ×72 ---
mul_142:
    SBC A,B
    RLCA
mul_72:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×143 → ×9 ---
mul_143:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
mul_9:
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×146 → ×144 ---
mul_146:
    ADD A,B
mul_144:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×148 → ×74 ---
mul_148:
    ADD A,A
mul_74:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×149 → ×37 ---
mul_149:
    ADD A,B
    ADD A,A
    ADD A,A
mul_37:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×150 → ×6 ---
mul_150:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
mul_6:
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×154 → ×152 → ×76 → ×38 ---
mul_154:
    ADD A,B
mul_152:
    ADD A,A
mul_76:
    ADD A,A
mul_38:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×156 → ×78 → ×20 ---
mul_156:
    ADD A,A
mul_78:
    SBC A,B
    RLCA
    ADD A,A
mul_20:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×157 → ×39 ---
mul_157:
    ADD A,B
    ADD A,A
    ADD A,A
mul_39:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×158 → ×80 ---
mul_158:
    SBC A,B
    RLCA
mul_80:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×162 → ×160 ---
mul_162:
    ADD A,B
mul_160:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×163 → ×41 ---
mul_163:
    SBC A,B
    RLCA
    ADD A,A
mul_41:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×164 → ×82 ---
mul_164:
    ADD A,A
mul_82:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×166 → ×84 → ×42 ---
mul_166:
    SBC A,B
    RLCA
mul_84:
    ADD A,A
mul_42:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×167 → ×21 ---
mul_167:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
mul_21:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

; --- Chain: ×170 → ×10 ---
mul_170:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
mul_10:
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

; --- Chain: ×171 → ×251 ---
mul_171:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
mul_251:
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×173 → ×214 → ×235 ---
mul_173:
    SBC A,B
    RLCA
mul_214:
    ADD A,A
mul_235:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×174 → ×215 ---
mul_174:
    ADD A,A
mul_215:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×175 → ×176 ---
mul_175:
    ADD A,B
mul_176:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×177 → ×216 ---
mul_177:
    SBC A,B
    RLCA
mul_216:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×178 → ×217 → ×236 ---
mul_178:
    ADD A,A
mul_217:
    SBC A,B
    RLCA
mul_236:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×179 → ×180 → ×218 → ×237 ---
mul_179:
    ADD A,B
mul_180:
    ADD A,A
mul_218:
    ADD A,A
mul_237:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×181 → ×253 ---
mul_181:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
mul_253:
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×182 → ×219 ---
mul_182:
    ADD A,A
mul_219:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×183 → ×184 ---
mul_183:
    ADD A,B
mul_184:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×185 → ×220 ---
mul_185:
    SBC A,B
    RLCA
mul_220:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×186 → ×238 → ×247 ---
mul_186:
    ADD A,A
    SBC A,B
    RLCA
mul_238:
    ADD A,A
mul_247:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×187 → ×188 → ×222 ---
mul_187:
    ADD A,B
mul_188:
    ADD A,A
mul_222:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×189 → ×190 → ×223 ---
mul_189:
    ADD A,B
mul_190:
    ADD A,A
mul_223:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×191 → ×255 ---
mul_191:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
mul_255:
    NEG
    RET

; --- Chain: ×192 → ×224 ---
mul_192:
    ADD A,A
mul_224:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    NEG
    RET

; --- Chain: ×195 → ×196 → ×226 → ×241 ---
mul_195:
    ADD A,B
mul_196:
    ADD A,A
mul_226:
    ADD A,A
mul_241:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×198 → ×227 ---
mul_198:
    ADD A,A
mul_227:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×200 → ×242 → ×249 ---
mul_200:
    ADD A,A
    ADD A,A
mul_242:
    ADD A,A
mul_249:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×203 → ×204 → ×230 → ×243 ---
mul_203:
    ADD A,B
mul_204:
    ADD A,A
mul_230:
    ADD A,A
mul_243:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×206 → ×231 ---
mul_206:
    ADD A,A
mul_231:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×207 → ×208 ---
mul_207:
    ADD A,B
mul_208:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×209 → ×232 ---
mul_209:
    SBC A,B
    RLCA
mul_232:
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×210 → ×244 ---
mul_210:
    ADD A,A
    SBC A,B
    RLCA
mul_244:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

; --- Chain: ×248 → ×252 → ×254 ---
mul_248:
    ADD A,A
mul_252:
    ADD A,A
mul_254:
    NEG
    RLA
    RET

; --- Standalone entries ---

mul_3:
    ADD A,B
    ADC A,A
    LD B,A
    RET

mul_5:
    ADD A,B
    ADD A,A
    ADC A,B
    LD B,A
    RET

mul_7:
    SBC A,B
    RLCA
    ADD A,A
    ADC A,B
    LD B,A
    RET

mul_15:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADC A,B
    LD B,A
    RET

mul_19:
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_22:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    LD B,A
    RLA
    RET

mul_27:
    SBC A,B
    RLCA
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    RLA
    LD B,A
    RET

mul_28:
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    LD B,A
    RLA
    RET

mul_29:
    ADD A,B
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    RLA
    LD B,A
    RET

mul_35:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_36:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    LD B,A
    RLA
    RET

mul_40:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    LD B,A
    RLA
    RET

mul_43:
    SBC A,B
    RLCA
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_45:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_47:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_49:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_51:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_53:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_55:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_57:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_59:
    SBC A,B
    RLCA
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_61:
    ADD A,B
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_63:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_65:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_66:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

mul_71:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_73:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_75:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_77:
    ADD A,B
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_79:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_81:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_83:
    SUB B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_85:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_88:
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

mul_89:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_90:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

mul_93:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_95:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_97:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_99:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_102:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

mul_105:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_107:
    SBC A,B
    RLCA
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_108:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

mul_109:
    ADD A,B
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_111:
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_112:
    ADD A,A
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

mul_113:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_114:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

mul_115:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_116:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    RLA
    RET

mul_117:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_119:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_121:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_125:
    SUB B
    SUB B
    SUB B
    RRA
    NEG
    SBC A,A
    RRCA
    LD B,A
    RET

mul_126:
    SUB B
    SBC A,B
    SRL A
    SBC A,A
    LD B,A
    ADD A,A
    RRCA
    RET

mul_127:
    SUB B
    RRA
    NEG
    ADC A,B
    LD B,A
    RRCA
    RET

mul_128:
    RRA
    ADC A,B
    SBC A,A
    RRCA
    RET

mul_133:
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    ADC A,B
    RRCA
    RLA
    LD B,A
    RRA
    RET

mul_135:
    SUB B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADC A,B
    RRCA
    RLA
    LD B,A
    RRA
    RET

mul_137:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADC A,B
    RRCA
    RLA
    LD B,A
    RRA
    RET

mul_141:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    ADC A,B
    RRCA
    RLA
    LD B,A
    RRA
    RET

mul_145:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    RLA
    LD B,A
    RET

mul_147:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    ADD A,B
    RLA
    LD B,A
    RET

mul_151:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_153:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_155:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_159:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_161:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_165:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_168:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    RLA
    RET

mul_169:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    RLA
    LD B,A
    RET

mul_172:
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_193:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_194:
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_197:
    SUB B
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_199:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_201:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_202:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_205:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_211:
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    LD B,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_212:
    ADD A,A
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_213:
    SBC A,B
    RLCA
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_221:
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_225:
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_228:
    ADD A,A
    ADD A,A
    SUB B
    ADD A,A
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_229:
    SBC A,B
    RLCA
    ADD A,A
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_233:
    SUB B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,B
    ADD A,B
    LD B,A
    NEG
    RET

mul_234:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,B
    LD B,A
    NEG
    RET

mul_239:
    ADD A,B
    ADD A,A
    ADD A,A
    ADD A,A
    ADD A,A
    LD B,A
    NEG
    RET

mul_240:
    NEG
    ADD A,A
    ADD A,A
    ADD A,A
    RLA
    RET

mul_245:
    SBC A,B
    RLCA
    ADD A,A
    ADD A,B
    ADD A,A
    LD B,A
    NEG
    RET

mul_246:
    ADD A,A
    ADD A,B
    ADD A,A
    ADD A,A
    LD B,A
    NEG
    RET

mul_250:
    SBC A,B
    RLCA
    NEG
    LD B,A
    RLA
    RET
