#!/usr/bin/env python3
"""Generate mul16_library.asm from mulopt16_complete.json.

The mul16 optimizer already generates sequences that end with ADD HL,HL
doublings, so literal suffix detection finds ~123 chains automatically
(every even k chains to ×2, multiples of 4 to ×4, powers of 2 to ×2^n, etc.)

Convention:
  Input:  HL = value (H=0, L=A, i.e. 8-bit value zero-extended to 16-bit)
          A = L (low byte, for use in initial LD C,A)
          B = 0
  Output: HL = HL * K
  Clobber: C, F (B=0 preserved)

Usage:
  LD A, value
  LD L, A
  LD H, 0
  CALL mul16_42
  ; HL now contains value * 42
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).parent.parent
JSON_IN = REPO / "data" / "mulopt16_complete.json"
ASM_OUT = REPO / "data" / "mul16_library.asm"


def load_table(path):
    with open(path) as f:
        entries = json.load(f)
    return {e["k"]: e for e in entries}


def verify_sequence(ops, k):
    """Simulate mul16 ops on all 256 inputs (H=0, L=a_in, B=0, A=a_in).
    Returns True if HL_out == a_in * k.
    """
    def exec_seq(ops, a_in):
        h, l, a, b, c = 0, a_in & 0xFF, a_in & 0xFF, 0, 0
        carry = False

        def hl():
            return (h << 8) | l

        def set_hl(v):
            nonlocal h, l
            v &= 0xFFFF
            h, l = v >> 8, v & 0xFF

        for op in ops:
            if op == "ADD HL,HL":
                v = hl() * 2
                carry = v > 0xFFFF
                set_hl(v)
            elif op == "ADD HL,BC":
                v = hl() + ((b << 8) | c)
                carry = v > 0xFFFF
                set_hl(v)
            elif op == "LD C,A":
                c = a
            elif op == "LD B,A":
                b = a
            elif op == "LD A,L":
                a = l
            elif op == "LD A,H":
                a = h
            elif op == "XOR A":
                a = 0
                carry = False
            elif op == "LD H,0":
                h = 0
            elif op == "LD L,A":
                l = a
            elif op == "SUB HL,BC":
                v = hl() - ((b << 8) | c)
                carry = v < 0
                set_hl(v)
            elif op == "SWAP_HL":
                h, l = l, h
            else:
                raise ValueError(f"Unknown mul16 op: {op!r}")
        return hl()

    for a_in in range(256):
        expected = (a_in * k) & 0xFFFF
        got = exec_seq(ops, a_in)
        if got != expected:
            return False, a_in, expected, got
    return True, None, None, None


def find_suffix_chains(by_k):
    """Find pairs where ops[k_short] is a genuine suffix of ops[k_long].
    Returns dict: k_long -> k_short (longest shared suffix wins).
    """
    suffix_map = {}
    for k_long, e_long in by_k.items():
        best_suffix_k = None
        best_suffix_len = 0
        ops_long = e_long["ops"]
        for k_short, e_short in by_k.items():
            if k_short == k_long:
                continue
            ops_short = e_short["ops"]
            n = len(ops_short)
            if n >= len(ops_long):
                continue
            if ops_long[-n:] == ops_short and n > best_suffix_len:
                best_suffix_k = k_short
                best_suffix_len = n
        if best_suffix_k is not None:
            suffix_map[k_long] = best_suffix_k
    return suffix_map


def build_chains(by_k, suffix_map):
    """Build valid linear fall-through chains by following suffix pointers.
    Sorted longest-first so longer chains own shared tails.
    """
    pointed_to = set(suffix_map.values())
    roots = sorted(k for k in suffix_map if k not in pointed_to)

    chains = []
    for root in roots:
        chain = [root]
        cur = root
        while cur in suffix_map:
            cur = suffix_map[cur]
            chain.append(cur)
        if len(chain) >= 2:
            chains.append(chain)

    chains.sort(key=lambda c: -len(c))
    return chains


def expand_op(op):
    """Expand pseudo-ops to real Z80 instructions."""
    if op == "SWAP_HL":
        return ["LD A,L", "LD L,H", "LD H,A"]
    elif op == "SUB HL,BC":
        return ["OR A", "SBC HL,BC"]
    return [op]


def emit_library(by_k, suffix_map):
    chains = build_chains(by_k, suffix_map)

    emitted = set()
    group_lines = []

    n_constants = len(by_k)
    n_chains = len(chains)

    header = f"""\
; Z80 Optimal Constant Multiply Library (16-bit: HL × K → HL)
; Generated by scripts/gen_mul16_library.py from mulopt16_complete.json
; (GPU brute-force, provably optimal sequences)
;
; {n_constants} constants (k=2..255), sequences in CORRECT execution order.
; {n_chains} fall-through chains (genuine suffix relationships only).
;
; Convention:
;   Input:  HL = value (H=0, L=A, i.e. 8-bit value zero-extended)
;           A  = L (low byte, for initial LD C,A save)
;           B  = 0 (implicit zero high byte of BC for ADD HL,BC)
;   Output: HL = HL * K  (mod 65536)
;   Clobber: C, F  (B remains 0)
;
; Usage:
;   LD A, value      ; 8-bit value to multiply
;   LD L, A
;   LD H, 0
;   CALL mul16_42
;   ; HL = value * 42
;
; Note: even-k sequences end with ADD HL,HL, enabling 123 doubling chains:
;   mul16_192 → mul16_96 → mul16_48 → ... → mul16_3 (×3 family)
;   mul16_128 → mul16_64 → mul16_32 → ... → mul16_2 (powers of 2)
;
; Repository: https://github.com/oisee/z80-optimizer
; License: MIT
;
"""

    def emit_chain(chain):
        ks = chain
        chain_label = " → ".join(f"×{k}" for k in ks)
        group_lines.append(f"; --- Chain: {chain_label} ---")
        for i, k in enumerate(ks):
            entry = by_k[k]
            group_lines.append(
                f"mul16_{k}:  ; ×{k}  ({entry['length']} insts, {entry['tstates']}T)"
            )
            if i + 1 < len(ks):
                next_k = ks[i + 1]
                next_ops = by_k[next_k]["ops"]
                unique_ops = entry["ops"][: len(entry["ops"]) - len(next_ops)]
            else:
                unique_ops = entry["ops"]
            for op in unique_ops:
                for eop in expand_op(op):
                    group_lines.append(f"    {eop}")
            emitted.add(k)
        group_lines.append("    RET")
        group_lines.append("")

    def emit_jp_prefix(k, chain):
        """Emit unique prefix of k in chain + JP to already-emitted tail."""
        entry = by_k[k]
        k_idx = chain.index(k)
        jp_target = next((chain[j] for j in range(k_idx + 1, len(chain)) if chain[j] in emitted), None)
        if jp_target is None:
            emit_standalone(k)
            return
        target_ops = by_k[jp_target]["ops"]
        unique_ops = entry["ops"][: len(entry["ops"]) - len(target_ops)]
        group_lines.append(
            f"mul16_{k}:  ; ×{k}  ({entry['length']} insts, {entry['tstates']}T)"
        )
        for op in unique_ops:
            for eop in expand_op(op):
                group_lines.append(f"    {eop}")
        group_lines.append(f"    JP mul16_{jp_target}")
        group_lines.append("")
        emitted.add(k)

    def emit_standalone(k):
        entry = by_k[k]
        group_lines.append(
            f"mul16_{k}:  ; ×{k}  ({entry['length']} insts, {entry['tstates']}T)"
        )
        for op in entry["ops"]:
            for eop in expand_op(op):
                group_lines.append(f"    {eop}")
        group_lines.append("    RET")
        group_lines.append("")
        emitted.add(k)

    for chain in chains:
        first_emitted_idx = next(
            (i for i, k in enumerate(chain) if k in emitted), None
        )
        if first_emitted_idx is None:
            emit_chain(chain)
        elif first_emitted_idx == 0:
            pass  # entire chain already emitted
        else:
            for i in range(first_emitted_idx):
                k = chain[i]
                if k not in emitted:
                    emit_jp_prefix(k, chain)

    for k in sorted(by_k.keys()):
        if k not in emitted:
            emit_standalone(k)

    return header + "\n".join(group_lines) + "\n"


def main():
    print(f"Loading {JSON_IN}...", file=sys.stderr)
    by_k = load_table(JSON_IN)
    print(f"  {len(by_k)} entries loaded", file=sys.stderr)

    # Verify all sequences
    bad = 0
    for k, e in sorted(by_k.items()):
        ok, a_in, expected, got = verify_sequence(e["ops"], k)
        if not ok:
            print(f"  VERIFY FAIL k={k}: ops={e['ops']}, a_in={a_in}, expected={expected}, got={got}", file=sys.stderr)
            bad += 1
    if bad == 0:
        print(f"  All {len(by_k)} sequences verified correct.", file=sys.stderr)
    else:
        print(f"  {bad} sequences FAILED verification!", file=sys.stderr)
        sys.exit(1)

    suffix_map = find_suffix_chains(by_k)
    print(f"  {len(suffix_map)} genuine fall-through chains found.", file=sys.stderr)

    chains = build_chains(by_k, suffix_map)
    long_chains = [(c, len(c)) for c in chains if len(c) >= 4]
    long_chains.sort(key=lambda x: -x[1])
    for chain, depth in long_chains[:8]:
        print(f"    {'→'.join(f'×{k}' for k in chain)}", file=sys.stderr)
    if len(long_chains) > 8:
        print(f"    ... ({len(long_chains)} chains of depth ≥4)", file=sys.stderr)

    asm = emit_library(by_k, suffix_map)

    with open(ASM_OUT, "w") as f:
        f.write(asm)
    print(f"Written {ASM_OUT} ({len(asm)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
