#!/usr/bin/env python3
"""Generate pkg/mulopt/mul16c_table.go from data/mulopt16c_complete.json.

Usage:
    python3 scripts/gen_mul16c_table.py data/mulopt16c_complete.json > pkg/mulopt/mul16c_table.go
"""

import json
import sys


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "data/mulopt16c_complete.json"
    with open(path) as f:
        data = json.load(f)

    found = [r for r in data if r.get("found", True) and "ops" in r]
    not_found = [r for r in data if not r.get("found", True)]

    print("// Code generated by scripts/gen_mul16c_table.py. DO NOT EDIT.")
    print("package mulopt")
    print()
    print("// Mul16cEntry is an HL×K→HL multiply sequence.")
    print("// Input:  HL = value to multiply")
    print("// Output: HL = HL × K (mod 65536)")
    print("// Scratch: BC and/or DE may be clobbered (see ClobbersBC, ClobbersDE).")
    print("type Mul16cEntry struct {")
    print("\tOps        []string // Z80 instructions")
    print("\tLen        int      // instruction count")
    print("\tTStates    int      // T-state cost")
    print("\tClobbersBC bool     // true if BC is clobbered")
    print("\tClobbersDE bool     // true if DE is clobbered")
    print("}")
    print()
    print("// Mul16cTable maps constant K (2..255) to the shortest known")
    print("// HL×K→HL sequence. Missing entries have no solution in ≤10 ops")
    print("// with the pure-ADD+copy op pool; use Emit16c(k) which falls back")
    print("// to decomposition or the A×K→HL table.")
    print(f"// Coverage: {len(found)}/254 constants solved.")

    not_found_ks = sorted(r["k"] for r in not_found)
    if not_found_ks:
        # Format as compact ranges
        ranges = []
        start = not_found_ks[0]
        prev = start
        for k in not_found_ks[1:]:
            if k == prev + 1:
                prev = k
            else:
                ranges.append(f"{start}" if start == prev else f"{start}-{prev}")
                start = prev = k
        ranges.append(f"{start}" if start == prev else f"{start}-{prev}")
        print(f"// Not found: K={', '.join(ranges)}")

    print("var Mul16cTable = map[int]*Mul16cEntry{")
    for r in sorted(found, key=lambda x: x["k"]):
        ops_go = ", ".join(f'"{op}"' for op in r["ops"])
        cbc = "true" if r.get("clobbers_bc") else "false"
        cde = "true" if r.get("clobbers_de") else "false"
        print(f'\t{r["k"]}: {{[]string{{{ops_go}}}, {r["length"]}, {r["tstates"]}, {cbc}, {cde}}},')
    print("}")
    print()
    print("// Emit16c returns the best known HL×K→HL sequence.")
    print("// If K is not in Mul16cTable, falls back to Emit16(k) via A register")
    print("// (adds preamble: LD A,L and postamble if needed).")
    print("// Returns (ops, tstates, clobbersBC, clobbersDE, ok).")
    print("func Emit16c(k int) ([]string, int, bool, bool, bool) {")
    print("\tif e, ok := Mul16cTable[k]; ok {")
    print("\t\treturn e.Ops, e.TStates, e.ClobbersBC, e.ClobbersDE, true")
    print("\t}")
    print("\treturn nil, 0, false, false, false")
    print("}")

    print(f"\n// Statistics written to stderr:", file=sys.stderr)
    print(f"//   Found:     {len(found)}/254", file=sys.stderr)
    print(f"//   Not found: {len(not_found)}/254", file=sys.stderr)
    if found:
        avg_t = sum(r["tstates"] for r in found) / len(found)
        avg_len = sum(r["length"] for r in found) / len(found)
        print(f"//   Avg len:   {avg_len:.1f} ops", file=sys.stderr)
        print(f"//   Avg T:     {avg_t:.1f}", file=sys.stderr)


if __name__ == "__main__":
    main()
